// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class ConnectToVideoCalibrationRequest implements flatbuffers.IUnpackableObject<ConnectToVideoCalibrationRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ConnectToVideoCalibrationRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConnectToVideoCalibrationRequest(bb:flatbuffers.ByteBuffer, obj?:ConnectToVideoCalibrationRequest):ConnectToVideoCalibrationRequest {
  return (obj || new ConnectToVideoCalibrationRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConnectToVideoCalibrationRequest(bb:flatbuffers.ByteBuffer, obj?:ConnectToVideoCalibrationRequest):ConnectToVideoCalibrationRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConnectToVideoCalibrationRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

offerSdp():string|null
offerSdp(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
offerSdp(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startConnectToVideoCalibrationRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addOfferSdp(builder:flatbuffers.Builder, offerSdpOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, offerSdpOffset, 0);
}

static endConnectToVideoCalibrationRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createConnectToVideoCalibrationRequest(builder:flatbuffers.Builder, offerSdpOffset:flatbuffers.Offset):flatbuffers.Offset {
  ConnectToVideoCalibrationRequest.startConnectToVideoCalibrationRequest(builder);
  ConnectToVideoCalibrationRequest.addOfferSdp(builder, offerSdpOffset);
  return ConnectToVideoCalibrationRequest.endConnectToVideoCalibrationRequest(builder);
}

unpack(): ConnectToVideoCalibrationRequestT {
  return new ConnectToVideoCalibrationRequestT(
    this.offerSdp()
  );
}


unpackTo(_o: ConnectToVideoCalibrationRequestT): void {
  _o.offerSdp = this.offerSdp();
}
}

export class ConnectToVideoCalibrationRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public offerSdp: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const offerSdp = (this.offerSdp !== null ? builder.createString(this.offerSdp!) : 0);

  return ConnectToVideoCalibrationRequest.createConnectToVideoCalibrationRequest(builder,
    offerSdp
  );
}
}
