// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class ConnectToVideoCalibrationResponse implements flatbuffers.IUnpackableObject<ConnectToVideoCalibrationResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ConnectToVideoCalibrationResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConnectToVideoCalibrationResponse(bb:flatbuffers.ByteBuffer, obj?:ConnectToVideoCalibrationResponse):ConnectToVideoCalibrationResponse {
  return (obj || new ConnectToVideoCalibrationResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConnectToVideoCalibrationResponse(bb:flatbuffers.ByteBuffer, obj?:ConnectToVideoCalibrationResponse):ConnectToVideoCalibrationResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConnectToVideoCalibrationResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

answerSdp():string|null
answerSdp(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
answerSdp(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startConnectToVideoCalibrationResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addAnswerSdp(builder:flatbuffers.Builder, answerSdpOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, answerSdpOffset, 0);
}

static endConnectToVideoCalibrationResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createConnectToVideoCalibrationResponse(builder:flatbuffers.Builder, answerSdpOffset:flatbuffers.Offset):flatbuffers.Offset {
  ConnectToVideoCalibrationResponse.startConnectToVideoCalibrationResponse(builder);
  ConnectToVideoCalibrationResponse.addAnswerSdp(builder, answerSdpOffset);
  return ConnectToVideoCalibrationResponse.endConnectToVideoCalibrationResponse(builder);
}

unpack(): ConnectToVideoCalibrationResponseT {
  return new ConnectToVideoCalibrationResponseT(
    this.answerSdp()
  );
}


unpackTo(_o: ConnectToVideoCalibrationResponseT): void {
  _o.answerSdp = this.answerSdp();
}
}

export class ConnectToVideoCalibrationResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public answerSdp: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const answerSdp = (this.answerSdp !== null ? builder.createString(this.answerSdp!) : 0);

  return ConnectToVideoCalibrationResponse.createConnectToVideoCalibrationResponse(builder,
    answerSdp
  );
}
}
