// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class EnableStayAlignedRequest implements flatbuffers.IUnpackableObject<EnableStayAlignedRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EnableStayAlignedRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEnableStayAlignedRequest(bb:flatbuffers.ByteBuffer, obj?:EnableStayAlignedRequest):EnableStayAlignedRequest {
  return (obj || new EnableStayAlignedRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEnableStayAlignedRequest(bb:flatbuffers.ByteBuffer, obj?:EnableStayAlignedRequest):EnableStayAlignedRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EnableStayAlignedRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startEnableStayAlignedRequest(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endEnableStayAlignedRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEnableStayAlignedRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  EnableStayAlignedRequest.startEnableStayAlignedRequest(builder);
  return EnableStayAlignedRequest.endEnableStayAlignedRequest(builder);
}

unpack(): EnableStayAlignedRequestT {
  return new EnableStayAlignedRequestT();
}


unpackTo(_o: EnableStayAlignedRequestT): void {}
}

export class EnableStayAlignedRequestT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return EnableStayAlignedRequest.createEnableStayAlignedRequest(builder);
}
}
