// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class RecordPFSRequest implements flatbuffers.IUnpackableObject<RecordPFSRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RecordPFSRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRecordPFSRequest(bb:flatbuffers.ByteBuffer, obj?:RecordPFSRequest):RecordPFSRequest {
  return (obj || new RecordPFSRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRecordPFSRequest(bb:flatbuffers.ByteBuffer, obj?:RecordPFSRequest):RecordPFSRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RecordPFSRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

durationSec():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

intervalSec():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startRecordPFSRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addDurationSec(builder:flatbuffers.Builder, durationSec:number) {
  builder.addFieldFloat32(0, durationSec, 0.0);
}

static addIntervalSec(builder:flatbuffers.Builder, intervalSec:number) {
  builder.addFieldFloat32(1, intervalSec, 0.0);
}

static endRecordPFSRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRecordPFSRequest(builder:flatbuffers.Builder, durationSec:number, intervalSec:number):flatbuffers.Offset {
  RecordPFSRequest.startRecordPFSRequest(builder);
  RecordPFSRequest.addDurationSec(builder, durationSec);
  RecordPFSRequest.addIntervalSec(builder, intervalSec);
  return RecordPFSRequest.endRecordPFSRequest(builder);
}

unpack(): RecordPFSRequestT {
  return new RecordPFSRequestT(
    this.durationSec(),
    this.intervalSec()
  );
}


unpackTo(_o: RecordPFSRequestT): void {
  _o.durationSec = this.durationSec();
  _o.intervalSec = this.intervalSec();
}
}

export class RecordPFSRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public durationSec: number = 0.0,
  public intervalSec: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return RecordPFSRequest.createRecordPFSRequest(builder,
    this.durationSec,
    this.intervalSec
  );
}
}
