// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { VideoCalibrationProcess } from '../../solarxr-protocol/rpc/video-calibration-process.js';


export class StartVideoCalibrationRequest implements flatbuffers.IUnpackableObject<StartVideoCalibrationRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StartVideoCalibrationRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStartVideoCalibrationRequest(bb:flatbuffers.ByteBuffer, obj?:StartVideoCalibrationRequest):StartVideoCalibrationRequest {
  return (obj || new StartVideoCalibrationRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStartVideoCalibrationRequest(bb:flatbuffers.ByteBuffer, obj?:StartVideoCalibrationRequest):StartVideoCalibrationRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StartVideoCalibrationRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

process():VideoCalibrationProcess {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : VideoCalibrationProcess.ALIGN_CAMERA;
}

static startStartVideoCalibrationRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addProcess(builder:flatbuffers.Builder, process:VideoCalibrationProcess) {
  builder.addFieldInt8(0, process, VideoCalibrationProcess.ALIGN_CAMERA);
}

static endStartVideoCalibrationRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStartVideoCalibrationRequest(builder:flatbuffers.Builder, process:VideoCalibrationProcess):flatbuffers.Offset {
  StartVideoCalibrationRequest.startStartVideoCalibrationRequest(builder);
  StartVideoCalibrationRequest.addProcess(builder, process);
  return StartVideoCalibrationRequest.endStartVideoCalibrationRequest(builder);
}

unpack(): StartVideoCalibrationRequestT {
  return new StartVideoCalibrationRequestT(
    this.process()
  );
}


unpackTo(_o: StartVideoCalibrationRequestT): void {
  _o.process = this.process();
}
}

export class StartVideoCalibrationRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public process: VideoCalibrationProcess = VideoCalibrationProcess.ALIGN_CAMERA
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return StartVideoCalibrationRequest.createStartVideoCalibrationRequest(builder,
    this.process
  );
}
}
