// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { VideoCalibrationCamera, VideoCalibrationCameraT } from '../../solarxr-protocol/rpc/video-calibration-camera.js';
import { VideoCalibrationStatus } from '../../solarxr-protocol/rpc/video-calibration-status.js';
import { VideoCalibrationTrackerStatus, VideoCalibrationTrackerStatusT } from '../../solarxr-protocol/rpc/video-calibration-tracker-status.js';


export class VideoCalibrationProgress implements flatbuffers.IUnpackableObject<VideoCalibrationProgressT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VideoCalibrationProgress {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVideoCalibrationProgress(bb:flatbuffers.ByteBuffer, obj?:VideoCalibrationProgress):VideoCalibrationProgress {
  return (obj || new VideoCalibrationProgress()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVideoCalibrationProgress(bb:flatbuffers.ByteBuffer, obj?:VideoCalibrationProgress):VideoCalibrationProgress {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VideoCalibrationProgress()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

status():VideoCalibrationStatus {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : VideoCalibrationStatus.NOT_STARTED;
}

camera(obj?:VideoCalibrationCamera):VideoCalibrationCamera|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new VideoCalibrationCamera()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

trackers(index: number, obj?:VideoCalibrationTrackerStatus):VideoCalibrationTrackerStatus|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new VideoCalibrationTrackerStatus()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

trackersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startVideoCalibrationProgress(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addStatus(builder:flatbuffers.Builder, status:VideoCalibrationStatus) {
  builder.addFieldInt8(0, status, VideoCalibrationStatus.NOT_STARTED);
}

static addCamera(builder:flatbuffers.Builder, cameraOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, cameraOffset, 0);
}

static addTrackers(builder:flatbuffers.Builder, trackersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, trackersOffset, 0);
}

static createTrackersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTrackersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endVideoCalibrationProgress(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): VideoCalibrationProgressT {
  return new VideoCalibrationProgressT(
    this.status(),
    (this.camera() !== null ? this.camera()!.unpack() : null),
    this.bb!.createObjList<VideoCalibrationTrackerStatus, VideoCalibrationTrackerStatusT>(this.trackers.bind(this), this.trackersLength())
  );
}


unpackTo(_o: VideoCalibrationProgressT): void {
  _o.status = this.status();
  _o.camera = (this.camera() !== null ? this.camera()!.unpack() : null);
  _o.trackers = this.bb!.createObjList<VideoCalibrationTrackerStatus, VideoCalibrationTrackerStatusT>(this.trackers.bind(this), this.trackersLength());
}
}

export class VideoCalibrationProgressT implements flatbuffers.IGeneratedObject {
constructor(
  public status: VideoCalibrationStatus = VideoCalibrationStatus.NOT_STARTED,
  public camera: VideoCalibrationCameraT|null = null,
  public trackers: (VideoCalibrationTrackerStatusT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const camera = (this.camera !== null ? this.camera!.pack(builder) : 0);
  const trackers = VideoCalibrationProgress.createTrackersVector(builder, builder.createObjectOffsetList(this.trackers));

  VideoCalibrationProgress.startVideoCalibrationProgress(builder);
  VideoCalibrationProgress.addStatus(builder, this.status);
  VideoCalibrationProgress.addCamera(builder, camera);
  VideoCalibrationProgress.addTrackers(builder, trackers);

  return VideoCalibrationProgress.endVideoCalibrationProgress(builder);
}
}
