// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Quat, QuatT } from '../../solarxr-protocol/datatypes/math/quat.js';
import { Vec3f, Vec3fT } from '../../solarxr-protocol/datatypes/math/vec3f.js';


export class VideoCalibrationCamera implements flatbuffers.IUnpackableObject<VideoCalibrationCameraT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VideoCalibrationCamera {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVideoCalibrationCamera(bb:flatbuffers.ByteBuffer, obj?:VideoCalibrationCamera):VideoCalibrationCamera {
  return (obj || new VideoCalibrationCamera()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVideoCalibrationCamera(bb:flatbuffers.ByteBuffer, obj?:VideoCalibrationCamera):VideoCalibrationCamera {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VideoCalibrationCamera()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

worldToCamera(obj?:Quat):Quat|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Quat()).__init(this.bb_pos + offset, this.bb!) : null;
}

worldOriginInCamera(obj?:Vec3f):Vec3f|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Vec3f()).__init(this.bb_pos + offset, this.bb!) : null;
}

fx():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

fy():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

tx():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

ty():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

width():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

height():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startVideoCalibrationCamera(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addWorldToCamera(builder:flatbuffers.Builder, worldToCameraOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, worldToCameraOffset, 0);
}

static addWorldOriginInCamera(builder:flatbuffers.Builder, worldOriginInCameraOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, worldOriginInCameraOffset, 0);
}

static addFx(builder:flatbuffers.Builder, fx:number) {
  builder.addFieldFloat32(2, fx, 0.0);
}

static addFy(builder:flatbuffers.Builder, fy:number) {
  builder.addFieldFloat32(3, fy, 0.0);
}

static addTx(builder:flatbuffers.Builder, tx:number) {
  builder.addFieldFloat32(4, tx, 0.0);
}

static addTy(builder:flatbuffers.Builder, ty:number) {
  builder.addFieldFloat32(5, ty, 0.0);
}

static addWidth(builder:flatbuffers.Builder, width:number) {
  builder.addFieldInt32(6, width, 0);
}

static addHeight(builder:flatbuffers.Builder, height:number) {
  builder.addFieldInt32(7, height, 0);
}

static endVideoCalibrationCamera(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): VideoCalibrationCameraT {
  return new VideoCalibrationCameraT(
    (this.worldToCamera() !== null ? this.worldToCamera()!.unpack() : null),
    (this.worldOriginInCamera() !== null ? this.worldOriginInCamera()!.unpack() : null),
    this.fx(),
    this.fy(),
    this.tx(),
    this.ty(),
    this.width(),
    this.height()
  );
}


unpackTo(_o: VideoCalibrationCameraT): void {
  _o.worldToCamera = (this.worldToCamera() !== null ? this.worldToCamera()!.unpack() : null);
  _o.worldOriginInCamera = (this.worldOriginInCamera() !== null ? this.worldOriginInCamera()!.unpack() : null);
  _o.fx = this.fx();
  _o.fy = this.fy();
  _o.tx = this.tx();
  _o.ty = this.ty();
  _o.width = this.width();
  _o.height = this.height();
}
}

export class VideoCalibrationCameraT implements flatbuffers.IGeneratedObject {
constructor(
  public worldToCamera: QuatT|null = null,
  public worldOriginInCamera: Vec3fT|null = null,
  public fx: number = 0.0,
  public fy: number = 0.0,
  public tx: number = 0.0,
  public ty: number = 0.0,
  public width: number = 0,
  public height: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  VideoCalibrationCamera.startVideoCalibrationCamera(builder);
  VideoCalibrationCamera.addWorldToCamera(builder, (this.worldToCamera !== null ? this.worldToCamera!.pack(builder) : 0));
  VideoCalibrationCamera.addWorldOriginInCamera(builder, (this.worldOriginInCamera !== null ? this.worldOriginInCamera!.pack(builder) : 0));
  VideoCalibrationCamera.addFx(builder, this.fx);
  VideoCalibrationCamera.addFy(builder, this.fy);
  VideoCalibrationCamera.addTx(builder, this.tx);
  VideoCalibrationCamera.addTy(builder, this.ty);
  VideoCalibrationCamera.addWidth(builder, this.width);
  VideoCalibrationCamera.addHeight(builder, this.height);

  return VideoCalibrationCamera.endVideoCalibrationCamera(builder);
}
}
