// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class VideoCalibrationForwardAndLeaningForwardNotAligned implements flatbuffers.IUnpackableObject<VideoCalibrationForwardAndLeaningForwardNotAlignedT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VideoCalibrationForwardAndLeaningForwardNotAligned {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVideoCalibrationForwardAndLeaningForwardNotAligned(bb:flatbuffers.ByteBuffer, obj?:VideoCalibrationForwardAndLeaningForwardNotAligned):VideoCalibrationForwardAndLeaningForwardNotAligned {
  return (obj || new VideoCalibrationForwardAndLeaningForwardNotAligned()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVideoCalibrationForwardAndLeaningForwardNotAligned(bb:flatbuffers.ByteBuffer, obj?:VideoCalibrationForwardAndLeaningForwardNotAligned):VideoCalibrationForwardAndLeaningForwardNotAligned {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VideoCalibrationForwardAndLeaningForwardNotAligned()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

yawDifference():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startVideoCalibrationForwardAndLeaningForwardNotAligned(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addYawDifference(builder:flatbuffers.Builder, yawDifference:number) {
  builder.addFieldFloat32(0, yawDifference, 0.0);
}

static endVideoCalibrationForwardAndLeaningForwardNotAligned(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVideoCalibrationForwardAndLeaningForwardNotAligned(builder:flatbuffers.Builder, yawDifference:number):flatbuffers.Offset {
  VideoCalibrationForwardAndLeaningForwardNotAligned.startVideoCalibrationForwardAndLeaningForwardNotAligned(builder);
  VideoCalibrationForwardAndLeaningForwardNotAligned.addYawDifference(builder, yawDifference);
  return VideoCalibrationForwardAndLeaningForwardNotAligned.endVideoCalibrationForwardAndLeaningForwardNotAligned(builder);
}

unpack(): VideoCalibrationForwardAndLeaningForwardNotAlignedT {
  return new VideoCalibrationForwardAndLeaningForwardNotAlignedT(
    this.yawDifference()
  );
}


unpackTo(_o: VideoCalibrationForwardAndLeaningForwardNotAlignedT): void {
  _o.yawDifference = this.yawDifference();
}
}

export class VideoCalibrationForwardAndLeaningForwardNotAlignedT implements flatbuffers.IGeneratedObject {
constructor(
  public yawDifference: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return VideoCalibrationForwardAndLeaningForwardNotAligned.createVideoCalibrationForwardAndLeaningForwardNotAligned(builder,
    this.yawDifference
  );
}
}
