// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { BodyPart } from '../../solarxr-protocol/datatypes/body-part.js';


export class VideoCalibrationTrackerStatus implements flatbuffers.IUnpackableObject<VideoCalibrationTrackerStatusT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VideoCalibrationTrackerStatus {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVideoCalibrationTrackerStatus(bb:flatbuffers.ByteBuffer, obj?:VideoCalibrationTrackerStatus):VideoCalibrationTrackerStatus {
  return (obj || new VideoCalibrationTrackerStatus()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVideoCalibrationTrackerStatus(bb:flatbuffers.ByteBuffer, obj?:VideoCalibrationTrackerStatus):VideoCalibrationTrackerStatus {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VideoCalibrationTrackerStatus()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

bodyPart():BodyPart {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : BodyPart.NONE;
}

aligned():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startVideoCalibrationTrackerStatus(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addBodyPart(builder:flatbuffers.Builder, bodyPart:BodyPart) {
  builder.addFieldInt8(0, bodyPart, BodyPart.NONE);
}

static addAligned(builder:flatbuffers.Builder, aligned:boolean) {
  builder.addFieldInt8(1, +aligned, +false);
}

static endVideoCalibrationTrackerStatus(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVideoCalibrationTrackerStatus(builder:flatbuffers.Builder, bodyPart:BodyPart, aligned:boolean):flatbuffers.Offset {
  VideoCalibrationTrackerStatus.startVideoCalibrationTrackerStatus(builder);
  VideoCalibrationTrackerStatus.addBodyPart(builder, bodyPart);
  VideoCalibrationTrackerStatus.addAligned(builder, aligned);
  return VideoCalibrationTrackerStatus.endVideoCalibrationTrackerStatus(builder);
}

unpack(): VideoCalibrationTrackerStatusT {
  return new VideoCalibrationTrackerStatusT(
    this.bodyPart(),
    this.aligned()
  );
}


unpackTo(_o: VideoCalibrationTrackerStatusT): void {
  _o.bodyPart = this.bodyPart();
  _o.aligned = this.aligned();
}
}

export class VideoCalibrationTrackerStatusT implements flatbuffers.IGeneratedObject {
constructor(
  public bodyPart: BodyPart = BodyPart.NONE,
  public aligned: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return VideoCalibrationTrackerStatus.createVideoCalibrationTrackerStatus(builder,
    this.bodyPart,
    this.aligned
  );
}
}
