// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { VideoCalibrationForwardAndLeaningForwardNotAligned, VideoCalibrationForwardAndLeaningForwardNotAlignedT } from '../../solarxr-protocol/rpc/video-calibration-forward-and-leaning-forward-not-aligned.js';
import { VideoCalibrationMissingTrackers, VideoCalibrationMissingTrackersT } from '../../solarxr-protocol/rpc/video-calibration-missing-trackers.js';


export class VideoCalibrationError implements flatbuffers.IUnpackableObject<VideoCalibrationErrorT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VideoCalibrationError {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVideoCalibrationError(bb:flatbuffers.ByteBuffer, obj?:VideoCalibrationError):VideoCalibrationError {
  return (obj || new VideoCalibrationError()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVideoCalibrationError(bb:flatbuffers.ByteBuffer, obj?:VideoCalibrationError):VideoCalibrationError {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VideoCalibrationError()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

missingPositionalTrackers(obj?:VideoCalibrationMissingTrackers):VideoCalibrationMissingTrackers|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new VideoCalibrationMissingTrackers()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

missingRequiredImuTrackers(obj?:VideoCalibrationMissingTrackers):VideoCalibrationMissingTrackers|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new VideoCalibrationMissingTrackers()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

forwardAndLeaningForwardNotAligned(obj?:VideoCalibrationForwardAndLeaningForwardNotAligned):VideoCalibrationForwardAndLeaningForwardNotAligned|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new VideoCalibrationForwardAndLeaningForwardNotAligned()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startVideoCalibrationError(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addMissingPositionalTrackers(builder:flatbuffers.Builder, missingPositionalTrackersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, missingPositionalTrackersOffset, 0);
}

static addMissingRequiredImuTrackers(builder:flatbuffers.Builder, missingRequiredImuTrackersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, missingRequiredImuTrackersOffset, 0);
}

static addForwardAndLeaningForwardNotAligned(builder:flatbuffers.Builder, forwardAndLeaningForwardNotAlignedOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, forwardAndLeaningForwardNotAlignedOffset, 0);
}

static endVideoCalibrationError(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): VideoCalibrationErrorT {
  return new VideoCalibrationErrorT(
    (this.missingPositionalTrackers() !== null ? this.missingPositionalTrackers()!.unpack() : null),
    (this.missingRequiredImuTrackers() !== null ? this.missingRequiredImuTrackers()!.unpack() : null),
    (this.forwardAndLeaningForwardNotAligned() !== null ? this.forwardAndLeaningForwardNotAligned()!.unpack() : null)
  );
}


unpackTo(_o: VideoCalibrationErrorT): void {
  _o.missingPositionalTrackers = (this.missingPositionalTrackers() !== null ? this.missingPositionalTrackers()!.unpack() : null);
  _o.missingRequiredImuTrackers = (this.missingRequiredImuTrackers() !== null ? this.missingRequiredImuTrackers()!.unpack() : null);
  _o.forwardAndLeaningForwardNotAligned = (this.forwardAndLeaningForwardNotAligned() !== null ? this.forwardAndLeaningForwardNotAligned()!.unpack() : null);
}
}

export class VideoCalibrationErrorT implements flatbuffers.IGeneratedObject {
constructor(
  public missingPositionalTrackers: VideoCalibrationMissingTrackersT|null = null,
  public missingRequiredImuTrackers: VideoCalibrationMissingTrackersT|null = null,
  public forwardAndLeaningForwardNotAligned: VideoCalibrationForwardAndLeaningForwardNotAlignedT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const missingPositionalTrackers = (this.missingPositionalTrackers !== null ? this.missingPositionalTrackers!.pack(builder) : 0);
  const missingRequiredImuTrackers = (this.missingRequiredImuTrackers !== null ? this.missingRequiredImuTrackers!.pack(builder) : 0);
  const forwardAndLeaningForwardNotAligned = (this.forwardAndLeaningForwardNotAligned !== null ? this.forwardAndLeaningForwardNotAligned!.pack(builder) : 0);

  VideoCalibrationError.startVideoCalibrationError(builder);
  VideoCalibrationError.addMissingPositionalTrackers(builder, missingPositionalTrackers);
  VideoCalibrationError.addMissingRequiredImuTrackers(builder, missingRequiredImuTrackers);
  VideoCalibrationError.addForwardAndLeaningForwardNotAligned(builder, forwardAndLeaningForwardNotAligned);

  return VideoCalibrationError.endVideoCalibrationError(builder);
}
}
