// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { BodyPart } from '../../solarxr-protocol/datatypes/body-part.js';


export class VideoCalibrationMissingTrackers implements flatbuffers.IUnpackableObject<VideoCalibrationMissingTrackersT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):VideoCalibrationMissingTrackers {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsVideoCalibrationMissingTrackers(bb:flatbuffers.ByteBuffer, obj?:VideoCalibrationMissingTrackers):VideoCalibrationMissingTrackers {
  return (obj || new VideoCalibrationMissingTrackers()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsVideoCalibrationMissingTrackers(bb:flatbuffers.ByteBuffer, obj?:VideoCalibrationMissingTrackers):VideoCalibrationMissingTrackers {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new VideoCalibrationMissingTrackers()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

missingTrackers(index: number):BodyPart|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

missingTrackersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

missingTrackersArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startVideoCalibrationMissingTrackers(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addMissingTrackers(builder:flatbuffers.Builder, missingTrackersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, missingTrackersOffset, 0);
}

static createMissingTrackersVector(builder:flatbuffers.Builder, data:BodyPart[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startMissingTrackersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endVideoCalibrationMissingTrackers(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createVideoCalibrationMissingTrackers(builder:flatbuffers.Builder, missingTrackersOffset:flatbuffers.Offset):flatbuffers.Offset {
  VideoCalibrationMissingTrackers.startVideoCalibrationMissingTrackers(builder);
  VideoCalibrationMissingTrackers.addMissingTrackers(builder, missingTrackersOffset);
  return VideoCalibrationMissingTrackers.endVideoCalibrationMissingTrackers(builder);
}

unpack(): VideoCalibrationMissingTrackersT {
  return new VideoCalibrationMissingTrackersT(
    this.bb!.createScalarList<BodyPart>(this.missingTrackers.bind(this), this.missingTrackersLength())
  );
}


unpackTo(_o: VideoCalibrationMissingTrackersT): void {
  _o.missingTrackers = this.bb!.createScalarList<BodyPart>(this.missingTrackers.bind(this), this.missingTrackersLength());
}
}

export class VideoCalibrationMissingTrackersT implements flatbuffers.IGeneratedObject {
constructor(
  public missingTrackers: (BodyPart)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const missingTrackers = VideoCalibrationMissingTrackers.createMissingTrackersVector(builder, this.missingTrackers);

  return VideoCalibrationMissingTrackers.createVideoCalibrationMissingTrackers(builder,
    missingTrackers
  );
}
}
