// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class ConnectToVideoCalibrationRequestT {
  private String offerSdp;

  public String getOfferSdp() { return offerSdp; }

  public void setOfferSdp(String offerSdp) { this.offerSdp = offerSdp; }


  public ConnectToVideoCalibrationRequestT() {
    this.offerSdp = null;
  }
}

