// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ConnectToVideoCalibrationResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static ConnectToVideoCalibrationResponse getRootAsConnectToVideoCalibrationResponse(ByteBuffer _bb) { return getRootAsConnectToVideoCalibrationResponse(_bb, new ConnectToVideoCalibrationResponse()); }
  public static ConnectToVideoCalibrationResponse getRootAsConnectToVideoCalibrationResponse(ByteBuffer _bb, ConnectToVideoCalibrationResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ConnectToVideoCalibrationResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String answerSdp() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer answerSdpAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer answerSdpInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createConnectToVideoCalibrationResponse(FlatBufferBuilder builder,
      int answerSdpOffset) {
    builder.startTable(1);
    ConnectToVideoCalibrationResponse.addAnswerSdp(builder, answerSdpOffset);
    return ConnectToVideoCalibrationResponse.endConnectToVideoCalibrationResponse(builder);
  }

  public static void startConnectToVideoCalibrationResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addAnswerSdp(FlatBufferBuilder builder, int answerSdpOffset) { builder.addOffset(0, answerSdpOffset, 0); }
  public static int endConnectToVideoCalibrationResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ConnectToVideoCalibrationResponse get(int j) { return get(new ConnectToVideoCalibrationResponse(), j); }
    public ConnectToVideoCalibrationResponse get(ConnectToVideoCalibrationResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public ConnectToVideoCalibrationResponseT unpack() {
    ConnectToVideoCalibrationResponseT _o = new ConnectToVideoCalibrationResponseT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(ConnectToVideoCalibrationResponseT _o) {
    String _oAnswerSdp = answerSdp();
    _o.setAnswerSdp(_oAnswerSdp);
  }
  public static int pack(FlatBufferBuilder builder, ConnectToVideoCalibrationResponseT _o) {
    if (_o == null) return 0;
    int _answerSdp = _o.getAnswerSdp() == null ? 0 : builder.createString(_o.getAnswerSdp());
    return createConnectToVideoCalibrationResponse(
      builder,
      _answerSdp);
  }
}

