// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ConnectToVideoCalibrationRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static ConnectToVideoCalibrationRequest getRootAsConnectToVideoCalibrationRequest(ByteBuffer _bb) { return getRootAsConnectToVideoCalibrationRequest(_bb, new ConnectToVideoCalibrationRequest()); }
  public static ConnectToVideoCalibrationRequest getRootAsConnectToVideoCalibrationRequest(ByteBuffer _bb, ConnectToVideoCalibrationRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ConnectToVideoCalibrationRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String offerSdp() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer offerSdpAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer offerSdpInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createConnectToVideoCalibrationRequest(FlatBufferBuilder builder,
      int offerSdpOffset) {
    builder.startTable(1);
    ConnectToVideoCalibrationRequest.addOfferSdp(builder, offerSdpOffset);
    return ConnectToVideoCalibrationRequest.endConnectToVideoCalibrationRequest(builder);
  }

  public static void startConnectToVideoCalibrationRequest(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addOfferSdp(FlatBufferBuilder builder, int offerSdpOffset) { builder.addOffset(0, offerSdpOffset, 0); }
  public static int endConnectToVideoCalibrationRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ConnectToVideoCalibrationRequest get(int j) { return get(new ConnectToVideoCalibrationRequest(), j); }
    public ConnectToVideoCalibrationRequest get(ConnectToVideoCalibrationRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public ConnectToVideoCalibrationRequestT unpack() {
    ConnectToVideoCalibrationRequestT _o = new ConnectToVideoCalibrationRequestT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(ConnectToVideoCalibrationRequestT _o) {
    String _oOfferSdp = offerSdp();
    _o.setOfferSdp(_oOfferSdp);
  }
  public static int pack(FlatBufferBuilder builder, ConnectToVideoCalibrationRequestT _o) {
    if (_o == null) return 0;
    int _offerSdp = _o.getOfferSdp() == null ? 0 : builder.createString(_o.getOfferSdp());
    return createConnectToVideoCalibrationRequest(
      builder,
      _offerSdp);
  }
}

