// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class RecordPFSRequestT {
  private float durationSec;
  private float intervalSec;

  public float getDurationSec() { return durationSec; }

  public void setDurationSec(float durationSec) { this.durationSec = durationSec; }

  public float getIntervalSec() { return intervalSec; }

  public void setIntervalSec(float intervalSec) { this.intervalSec = intervalSec; }


  public RecordPFSRequestT() {
    this.durationSec = 0.0f;
    this.intervalSec = 0.0f;
  }
}

