// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RecordPFSRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static RecordPFSRequest getRootAsRecordPFSRequest(ByteBuffer _bb) { return getRootAsRecordPFSRequest(_bb, new RecordPFSRequest()); }
  public static RecordPFSRequest getRootAsRecordPFSRequest(ByteBuffer _bb, RecordPFSRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RecordPFSRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float durationSec() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float intervalSec() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createRecordPFSRequest(FlatBufferBuilder builder,
      float durationSec,
      float intervalSec) {
    builder.startTable(2);
    RecordPFSRequest.addIntervalSec(builder, intervalSec);
    RecordPFSRequest.addDurationSec(builder, durationSec);
    return RecordPFSRequest.endRecordPFSRequest(builder);
  }

  public static void startRecordPFSRequest(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addDurationSec(FlatBufferBuilder builder, float durationSec) { builder.addFloat(0, durationSec, 0.0f); }
  public static void addIntervalSec(FlatBufferBuilder builder, float intervalSec) { builder.addFloat(1, intervalSec, 0.0f); }
  public static int endRecordPFSRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RecordPFSRequest get(int j) { return get(new RecordPFSRequest(), j); }
    public RecordPFSRequest get(RecordPFSRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public RecordPFSRequestT unpack() {
    RecordPFSRequestT _o = new RecordPFSRequestT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(RecordPFSRequestT _o) {
    float _oDurationSec = durationSec();
    _o.setDurationSec(_oDurationSec);
    float _oIntervalSec = intervalSec();
    _o.setIntervalSec(_oIntervalSec);
  }
  public static int pack(FlatBufferBuilder builder, RecordPFSRequestT _o) {
    if (_o == null) return 0;
    return createRecordPFSRequest(
      builder,
      _o.getDurationSec(),
      _o.getIntervalSec());
  }
}

