// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class RecordPFSResponseT {
  private int[] data;

  public int[] getData() { return data; }

  public void setData(int[] data) { this.data = data; }


  public RecordPFSResponseT() {
    this.data = null;
  }
}

