// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RecordPFSResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static RecordPFSResponse getRootAsRecordPFSResponse(ByteBuffer _bb) { return getRootAsRecordPFSResponse(_bb, new RecordPFSResponse()); }
  public static RecordPFSResponse getRootAsRecordPFSResponse(ByteBuffer _bb, RecordPFSResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RecordPFSResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int data(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int dataLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector dataVector() { return dataVector(new ByteVector()); }
  public ByteVector dataVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer dataAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer dataInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createRecordPFSResponse(FlatBufferBuilder builder,
      int dataOffset) {
    builder.startTable(1);
    RecordPFSResponse.addData(builder, dataOffset);
    return RecordPFSResponse.endRecordPFSResponse(builder);
  }

  public static void startRecordPFSResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addData(FlatBufferBuilder builder, int dataOffset) { builder.addOffset(0, dataOffset, 0); }
  public static int createDataVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createDataVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startDataVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endRecordPFSResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RecordPFSResponse get(int j) { return get(new RecordPFSResponse(), j); }
    public RecordPFSResponse get(RecordPFSResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public RecordPFSResponseT unpack() {
    RecordPFSResponseT _o = new RecordPFSResponseT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(RecordPFSResponseT _o) {
    int[] _oData = new int[dataLength()];
    for (int _j = 0; _j < dataLength(); ++_j) {_oData[_j] = data(_j);}
    _o.setData(_oData);
  }
  public static int pack(FlatBufferBuilder builder, RecordPFSResponseT _o) {
    if (_o == null) return 0;
    int _data = 0;
    if (_o.getData() != null) {
      byte[] __data = new byte[_o.getData().length];
      int _j = 0;
      for (int _e : _o.getData()) { __data[_j] = (byte) _e; _j++;}
      _data = createDataVector(builder, __data);
    }
    return createRecordPFSResponse(
      builder,
      _data);
  }
}

