// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

@SuppressWarnings("unused")
public final class ResetBodyPose {
  private ResetBodyPose() { }
  public static final int SKIING = 0;
  public static final int SITTING_LEANING_BACK = 1;

  public static final String[] names = { "SKIING", "SITTING_LEANING_BACK", };

  public static String name(int e) { return names[e]; }
}

