// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class StartVideoCalibrationRequestT {
  private int process;

  public int getProcess() { return process; }

  public void setProcess(int process) { this.process = process; }


  public StartVideoCalibrationRequestT() {
    this.process = 0;
  }
}

