// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StartVideoCalibrationRequest extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static StartVideoCalibrationRequest getRootAsStartVideoCalibrationRequest(ByteBuffer _bb) { return getRootAsStartVideoCalibrationRequest(_bb, new StartVideoCalibrationRequest()); }
  public static StartVideoCalibrationRequest getRootAsStartVideoCalibrationRequest(ByteBuffer _bb, StartVideoCalibrationRequest obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StartVideoCalibrationRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int process() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createStartVideoCalibrationRequest(FlatBufferBuilder builder,
      int process) {
    builder.startTable(1);
    StartVideoCalibrationRequest.addProcess(builder, process);
    return StartVideoCalibrationRequest.endStartVideoCalibrationRequest(builder);
  }

  public static void startStartVideoCalibrationRequest(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addProcess(FlatBufferBuilder builder, int process) { builder.addByte(0, (byte) process, (byte) 0); }
  public static int endStartVideoCalibrationRequest(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StartVideoCalibrationRequest get(int j) { return get(new StartVideoCalibrationRequest(), j); }
    public StartVideoCalibrationRequest get(StartVideoCalibrationRequest obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public StartVideoCalibrationRequestT unpack() {
    StartVideoCalibrationRequestT _o = new StartVideoCalibrationRequestT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(StartVideoCalibrationRequestT _o) {
    int _oProcess = process();
    _o.setProcess(_oProcess);
  }
  public static int pack(FlatBufferBuilder builder, StartVideoCalibrationRequestT _o) {
    if (_o == null) return 0;
    return createStartVideoCalibrationRequest(
      builder,
      _o.getProcess());
  }
}

