// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StayAlignedSettings extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static StayAlignedSettings getRootAsStayAlignedSettings(ByteBuffer _bb) { return getRootAsStayAlignedSettings(_bb, new StayAlignedSettings()); }
  public static StayAlignedSettings getRootAsStayAlignedSettings(ByteBuffer _bb, StayAlignedSettings obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StayAlignedSettings __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean enabled() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean extraYawCorrection() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public boolean hideYawCorrection() { int o = __offset(8); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public float standingUpperLegAngle() { int o = __offset(10); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float standingLowerLegAngle() { int o = __offset(12); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float standingFootAngle() { int o = __offset(14); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float sittingUpperLegAngle() { int o = __offset(16); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float sittingLowerLegAngle() { int o = __offset(18); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float sittingFootAngle() { int o = __offset(20); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float flatUpperLegAngle() { int o = __offset(22); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float flatLowerLegAngle() { int o = __offset(24); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float flatFootAngle() { int o = __offset(26); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createStayAlignedSettings(FlatBufferBuilder builder,
      boolean enabled,
      boolean extraYawCorrection,
      boolean hideYawCorrection,
      float standingUpperLegAngle,
      float standingLowerLegAngle,
      float standingFootAngle,
      float sittingUpperLegAngle,
      float sittingLowerLegAngle,
      float sittingFootAngle,
      float flatUpperLegAngle,
      float flatLowerLegAngle,
      float flatFootAngle) {
    builder.startTable(12);
    StayAlignedSettings.addFlatFootAngle(builder, flatFootAngle);
    StayAlignedSettings.addFlatLowerLegAngle(builder, flatLowerLegAngle);
    StayAlignedSettings.addFlatUpperLegAngle(builder, flatUpperLegAngle);
    StayAlignedSettings.addSittingFootAngle(builder, sittingFootAngle);
    StayAlignedSettings.addSittingLowerLegAngle(builder, sittingLowerLegAngle);
    StayAlignedSettings.addSittingUpperLegAngle(builder, sittingUpperLegAngle);
    StayAlignedSettings.addStandingFootAngle(builder, standingFootAngle);
    StayAlignedSettings.addStandingLowerLegAngle(builder, standingLowerLegAngle);
    StayAlignedSettings.addStandingUpperLegAngle(builder, standingUpperLegAngle);
    StayAlignedSettings.addHideYawCorrection(builder, hideYawCorrection);
    StayAlignedSettings.addExtraYawCorrection(builder, extraYawCorrection);
    StayAlignedSettings.addEnabled(builder, enabled);
    return StayAlignedSettings.endStayAlignedSettings(builder);
  }

  public static void startStayAlignedSettings(FlatBufferBuilder builder) { builder.startTable(12); }
  public static void addEnabled(FlatBufferBuilder builder, boolean enabled) { builder.addBoolean(0, enabled, false); }
  public static void addExtraYawCorrection(FlatBufferBuilder builder, boolean extraYawCorrection) { builder.addBoolean(1, extraYawCorrection, false); }
  public static void addHideYawCorrection(FlatBufferBuilder builder, boolean hideYawCorrection) { builder.addBoolean(2, hideYawCorrection, false); }
  public static void addStandingUpperLegAngle(FlatBufferBuilder builder, float standingUpperLegAngle) { builder.addFloat(3, standingUpperLegAngle, 0.0f); }
  public static void addStandingLowerLegAngle(FlatBufferBuilder builder, float standingLowerLegAngle) { builder.addFloat(4, standingLowerLegAngle, 0.0f); }
  public static void addStandingFootAngle(FlatBufferBuilder builder, float standingFootAngle) { builder.addFloat(5, standingFootAngle, 0.0f); }
  public static void addSittingUpperLegAngle(FlatBufferBuilder builder, float sittingUpperLegAngle) { builder.addFloat(6, sittingUpperLegAngle, 0.0f); }
  public static void addSittingLowerLegAngle(FlatBufferBuilder builder, float sittingLowerLegAngle) { builder.addFloat(7, sittingLowerLegAngle, 0.0f); }
  public static void addSittingFootAngle(FlatBufferBuilder builder, float sittingFootAngle) { builder.addFloat(8, sittingFootAngle, 0.0f); }
  public static void addFlatUpperLegAngle(FlatBufferBuilder builder, float flatUpperLegAngle) { builder.addFloat(9, flatUpperLegAngle, 0.0f); }
  public static void addFlatLowerLegAngle(FlatBufferBuilder builder, float flatLowerLegAngle) { builder.addFloat(10, flatLowerLegAngle, 0.0f); }
  public static void addFlatFootAngle(FlatBufferBuilder builder, float flatFootAngle) { builder.addFloat(11, flatFootAngle, 0.0f); }
  public static int endStayAlignedSettings(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StayAlignedSettings get(int j) { return get(new StayAlignedSettings(), j); }
    public StayAlignedSettings get(StayAlignedSettings obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public StayAlignedSettingsT unpack() {
    StayAlignedSettingsT _o = new StayAlignedSettingsT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(StayAlignedSettingsT _o) {
    boolean _oEnabled = enabled();
    _o.setEnabled(_oEnabled);
    boolean _oExtraYawCorrection = extraYawCorrection();
    _o.setExtraYawCorrection(_oExtraYawCorrection);
    boolean _oHideYawCorrection = hideYawCorrection();
    _o.setHideYawCorrection(_oHideYawCorrection);
    float _oStandingUpperLegAngle = standingUpperLegAngle();
    _o.setStandingUpperLegAngle(_oStandingUpperLegAngle);
    float _oStandingLowerLegAngle = standingLowerLegAngle();
    _o.setStandingLowerLegAngle(_oStandingLowerLegAngle);
    float _oStandingFootAngle = standingFootAngle();
    _o.setStandingFootAngle(_oStandingFootAngle);
    float _oSittingUpperLegAngle = sittingUpperLegAngle();
    _o.setSittingUpperLegAngle(_oSittingUpperLegAngle);
    float _oSittingLowerLegAngle = sittingLowerLegAngle();
    _o.setSittingLowerLegAngle(_oSittingLowerLegAngle);
    float _oSittingFootAngle = sittingFootAngle();
    _o.setSittingFootAngle(_oSittingFootAngle);
    float _oFlatUpperLegAngle = flatUpperLegAngle();
    _o.setFlatUpperLegAngle(_oFlatUpperLegAngle);
    float _oFlatLowerLegAngle = flatLowerLegAngle();
    _o.setFlatLowerLegAngle(_oFlatLowerLegAngle);
    float _oFlatFootAngle = flatFootAngle();
    _o.setFlatFootAngle(_oFlatFootAngle);
  }
  public static int pack(FlatBufferBuilder builder, StayAlignedSettingsT _o) {
    if (_o == null) return 0;
    return createStayAlignedSettings(
      builder,
      _o.getEnabled(),
      _o.getExtraYawCorrection(),
      _o.getHideYawCorrection(),
      _o.getStandingUpperLegAngle(),
      _o.getStandingLowerLegAngle(),
      _o.getStandingFootAngle(),
      _o.getSittingUpperLegAngle(),
      _o.getSittingLowerLegAngle(),
      _o.getSittingFootAngle(),
      _o.getFlatUpperLegAngle(),
      _o.getFlatLowerLegAngle(),
      _o.getFlatFootAngle());
  }
}

