// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class VideoCalibrationMissingTrackersT {
  private int[] missingTrackers;

  public int[] getMissingTrackers() { return missingTrackers; }

  public void setMissingTrackers(int[] missingTrackers) { this.missingTrackers = missingTrackers; }


  public VideoCalibrationMissingTrackersT() {
    this.missingTrackers = null;
  }
}

