// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class VideoCalibrationForwardAndLeaningForwardNotAligned extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static VideoCalibrationForwardAndLeaningForwardNotAligned getRootAsVideoCalibrationForwardAndLeaningForwardNotAligned(ByteBuffer _bb) { return getRootAsVideoCalibrationForwardAndLeaningForwardNotAligned(_bb, new VideoCalibrationForwardAndLeaningForwardNotAligned()); }
  public static VideoCalibrationForwardAndLeaningForwardNotAligned getRootAsVideoCalibrationForwardAndLeaningForwardNotAligned(ByteBuffer _bb, VideoCalibrationForwardAndLeaningForwardNotAligned obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public VideoCalibrationForwardAndLeaningForwardNotAligned __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float yawDifference() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createVideoCalibrationForwardAndLeaningForwardNotAligned(FlatBufferBuilder builder,
      float yawDifference) {
    builder.startTable(1);
    VideoCalibrationForwardAndLeaningForwardNotAligned.addYawDifference(builder, yawDifference);
    return VideoCalibrationForwardAndLeaningForwardNotAligned.endVideoCalibrationForwardAndLeaningForwardNotAligned(builder);
  }

  public static void startVideoCalibrationForwardAndLeaningForwardNotAligned(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addYawDifference(FlatBufferBuilder builder, float yawDifference) { builder.addFloat(0, yawDifference, 0.0f); }
  public static int endVideoCalibrationForwardAndLeaningForwardNotAligned(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public VideoCalibrationForwardAndLeaningForwardNotAligned get(int j) { return get(new VideoCalibrationForwardAndLeaningForwardNotAligned(), j); }
    public VideoCalibrationForwardAndLeaningForwardNotAligned get(VideoCalibrationForwardAndLeaningForwardNotAligned obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public VideoCalibrationForwardAndLeaningForwardNotAlignedT unpack() {
    VideoCalibrationForwardAndLeaningForwardNotAlignedT _o = new VideoCalibrationForwardAndLeaningForwardNotAlignedT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(VideoCalibrationForwardAndLeaningForwardNotAlignedT _o) {
    float _oYawDifference = yawDifference();
    _o.setYawDifference(_oYawDifference);
  }
  public static int pack(FlatBufferBuilder builder, VideoCalibrationForwardAndLeaningForwardNotAlignedT _o) {
    if (_o == null) return 0;
    return createVideoCalibrationForwardAndLeaningForwardNotAligned(
      builder,
      _o.getYawDifference());
  }
}

