// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class VideoCalibrationTrackerStatusT {
  private int bodyPart;
  private boolean aligned;

  public int getBodyPart() { return bodyPart; }

  public void setBodyPart(int bodyPart) { this.bodyPart = bodyPart; }

  public boolean getAligned() { return aligned; }

  public void setAligned(boolean aligned) { this.aligned = aligned; }


  public VideoCalibrationTrackerStatusT() {
    this.bodyPart = 0;
    this.aligned = false;
  }
}

