// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class VideoCalibrationError extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static VideoCalibrationError getRootAsVideoCalibrationError(ByteBuffer _bb) { return getRootAsVideoCalibrationError(_bb, new VideoCalibrationError()); }
  public static VideoCalibrationError getRootAsVideoCalibrationError(ByteBuffer _bb, VideoCalibrationError obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public VideoCalibrationError __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public solarxr_protocol.rpc.VideoCalibrationMissingTrackers missingPositionalTrackers() { return missingPositionalTrackers(new solarxr_protocol.rpc.VideoCalibrationMissingTrackers()); }
  public solarxr_protocol.rpc.VideoCalibrationMissingTrackers missingPositionalTrackers(solarxr_protocol.rpc.VideoCalibrationMissingTrackers obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public solarxr_protocol.rpc.VideoCalibrationMissingTrackers missingRequiredImuTrackers() { return missingRequiredImuTrackers(new solarxr_protocol.rpc.VideoCalibrationMissingTrackers()); }
  public solarxr_protocol.rpc.VideoCalibrationMissingTrackers missingRequiredImuTrackers(solarxr_protocol.rpc.VideoCalibrationMissingTrackers obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public solarxr_protocol.rpc.VideoCalibrationForwardAndLeaningForwardNotAligned forwardAndLeaningForwardNotAligned() { return forwardAndLeaningForwardNotAligned(new solarxr_protocol.rpc.VideoCalibrationForwardAndLeaningForwardNotAligned()); }
  public solarxr_protocol.rpc.VideoCalibrationForwardAndLeaningForwardNotAligned forwardAndLeaningForwardNotAligned(solarxr_protocol.rpc.VideoCalibrationForwardAndLeaningForwardNotAligned obj) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createVideoCalibrationError(FlatBufferBuilder builder,
      int missingPositionalTrackersOffset,
      int missingRequiredImuTrackersOffset,
      int forwardAndLeaningForwardNotAlignedOffset) {
    builder.startTable(3);
    VideoCalibrationError.addForwardAndLeaningForwardNotAligned(builder, forwardAndLeaningForwardNotAlignedOffset);
    VideoCalibrationError.addMissingRequiredImuTrackers(builder, missingRequiredImuTrackersOffset);
    VideoCalibrationError.addMissingPositionalTrackers(builder, missingPositionalTrackersOffset);
    return VideoCalibrationError.endVideoCalibrationError(builder);
  }

  public static void startVideoCalibrationError(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addMissingPositionalTrackers(FlatBufferBuilder builder, int missingPositionalTrackersOffset) { builder.addOffset(0, missingPositionalTrackersOffset, 0); }
  public static void addMissingRequiredImuTrackers(FlatBufferBuilder builder, int missingRequiredImuTrackersOffset) { builder.addOffset(1, missingRequiredImuTrackersOffset, 0); }
  public static void addForwardAndLeaningForwardNotAligned(FlatBufferBuilder builder, int forwardAndLeaningForwardNotAlignedOffset) { builder.addOffset(2, forwardAndLeaningForwardNotAlignedOffset, 0); }
  public static int endVideoCalibrationError(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public VideoCalibrationError get(int j) { return get(new VideoCalibrationError(), j); }
    public VideoCalibrationError get(VideoCalibrationError obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public VideoCalibrationErrorT unpack() {
    VideoCalibrationErrorT _o = new VideoCalibrationErrorT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(VideoCalibrationErrorT _o) {
    if (missingPositionalTrackers() != null) _o.setMissingPositionalTrackers(missingPositionalTrackers().unpack());
    else _o.setMissingPositionalTrackers(null);
    if (missingRequiredImuTrackers() != null) _o.setMissingRequiredImuTrackers(missingRequiredImuTrackers().unpack());
    else _o.setMissingRequiredImuTrackers(null);
    if (forwardAndLeaningForwardNotAligned() != null) _o.setForwardAndLeaningForwardNotAligned(forwardAndLeaningForwardNotAligned().unpack());
    else _o.setForwardAndLeaningForwardNotAligned(null);
  }
  public static int pack(FlatBufferBuilder builder, VideoCalibrationErrorT _o) {
    if (_o == null) return 0;
    int _missingPositionalTrackers = _o.getMissingPositionalTrackers() == null ? 0 : solarxr_protocol.rpc.VideoCalibrationMissingTrackers.pack(builder, _o.getMissingPositionalTrackers());
    int _missingRequiredImuTrackers = _o.getMissingRequiredImuTrackers() == null ? 0 : solarxr_protocol.rpc.VideoCalibrationMissingTrackers.pack(builder, _o.getMissingRequiredImuTrackers());
    int _forwardAndLeaningForwardNotAligned = _o.getForwardAndLeaningForwardNotAligned() == null ? 0 : solarxr_protocol.rpc.VideoCalibrationForwardAndLeaningForwardNotAligned.pack(builder, _o.getForwardAndLeaningForwardNotAligned());
    return createVideoCalibrationError(
      builder,
      _missingPositionalTrackers,
      _missingRequiredImuTrackers,
      _forwardAndLeaningForwardNotAligned);
  }
}

