// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class VideoCalibrationTrackerStatus extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static VideoCalibrationTrackerStatus getRootAsVideoCalibrationTrackerStatus(ByteBuffer _bb) { return getRootAsVideoCalibrationTrackerStatus(_bb, new VideoCalibrationTrackerStatus()); }
  public static VideoCalibrationTrackerStatus getRootAsVideoCalibrationTrackerStatus(ByteBuffer _bb, VideoCalibrationTrackerStatus obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public VideoCalibrationTrackerStatus __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int bodyPart() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public boolean aligned() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createVideoCalibrationTrackerStatus(FlatBufferBuilder builder,
      int bodyPart,
      boolean aligned) {
    builder.startTable(2);
    VideoCalibrationTrackerStatus.addAligned(builder, aligned);
    VideoCalibrationTrackerStatus.addBodyPart(builder, bodyPart);
    return VideoCalibrationTrackerStatus.endVideoCalibrationTrackerStatus(builder);
  }

  public static void startVideoCalibrationTrackerStatus(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addBodyPart(FlatBufferBuilder builder, int bodyPart) { builder.addByte(0, (byte) bodyPart, (byte) 0); }
  public static void addAligned(FlatBufferBuilder builder, boolean aligned) { builder.addBoolean(1, aligned, false); }
  public static int endVideoCalibrationTrackerStatus(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public VideoCalibrationTrackerStatus get(int j) { return get(new VideoCalibrationTrackerStatus(), j); }
    public VideoCalibrationTrackerStatus get(VideoCalibrationTrackerStatus obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public VideoCalibrationTrackerStatusT unpack() {
    VideoCalibrationTrackerStatusT _o = new VideoCalibrationTrackerStatusT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(VideoCalibrationTrackerStatusT _o) {
    int _oBodyPart = bodyPart();
    _o.setBodyPart(_oBodyPart);
    boolean _oAligned = aligned();
    _o.setAligned(_oAligned);
  }
  public static int pack(FlatBufferBuilder builder, VideoCalibrationTrackerStatusT _o) {
    if (_o == null) return 0;
    return createVideoCalibrationTrackerStatus(
      builder,
      _o.getBodyPart(),
      _o.getAligned());
  }
}

