// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

@SuppressWarnings("unused")
public final class VideoCalibrationStatus {
  private VideoCalibrationStatus() { }
  public static final int NOT_STARTED = 0;
  public static final int CONNECTING_TO_SERVER = 1;
  public static final int CONNECTING_TO_WEBCAM = 2;
  public static final int WAITING_FOR_USER_START = 3;
  public static final int SOLVING_CAMERA_EXTRINSIC = 4;
  public static final int CAPTURING_FORWARD_POSE = 5;
  public static final int CAPTURING_LEANING_FORWARD_POSE = 6;
  public static final int ALIGNING_UPPER_BODY_TRACKERS = 7;
  public static final int ALIGNING_REMAINING_TRACKERS = 8;
  public static final int OPTIMIZING_BODY_PROPORTIONS = 9;
  public static final int COMPLETE = 10;

  public static final String[] names = { "NOT_STARTED", "CONNECTING_TO_SERVER", "CONNECTING_TO_WEBCAM", "WAITING_FOR_USER_START", "SOLVING_CAMERA_EXTRINSIC", "CAPTURING_FORWARD_POSE", "CAPTURING_LEANING_FORWARD_POSE", "ALIGNING_UPPER_BODY_TRACKERS", "ALIGNING_REMAINING_TRACKERS", "OPTIMIZING_BODY_PROPORTIONS", "COMPLETE", };

  public static String name(int e) { return names[e]; }
}

