// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class VideoCalibrationProgress extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static VideoCalibrationProgress getRootAsVideoCalibrationProgress(ByteBuffer _bb) { return getRootAsVideoCalibrationProgress(_bb, new VideoCalibrationProgress()); }
  public static VideoCalibrationProgress getRootAsVideoCalibrationProgress(ByteBuffer _bb, VideoCalibrationProgress obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public VideoCalibrationProgress __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int status() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }
  public solarxr_protocol.rpc.VideoCalibrationCamera camera() { return camera(new solarxr_protocol.rpc.VideoCalibrationCamera()); }
  public solarxr_protocol.rpc.VideoCalibrationCamera camera(solarxr_protocol.rpc.VideoCalibrationCamera obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public solarxr_protocol.rpc.VideoCalibrationTrackerStatus trackers(int j) { return trackers(new solarxr_protocol.rpc.VideoCalibrationTrackerStatus(), j); }
  public solarxr_protocol.rpc.VideoCalibrationTrackerStatus trackers(solarxr_protocol.rpc.VideoCalibrationTrackerStatus obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int trackersLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public solarxr_protocol.rpc.VideoCalibrationTrackerStatus.Vector trackersVector() { return trackersVector(new solarxr_protocol.rpc.VideoCalibrationTrackerStatus.Vector()); }
  public solarxr_protocol.rpc.VideoCalibrationTrackerStatus.Vector trackersVector(solarxr_protocol.rpc.VideoCalibrationTrackerStatus.Vector obj) { int o = __offset(8); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createVideoCalibrationProgress(FlatBufferBuilder builder,
      int status,
      int cameraOffset,
      int trackersOffset) {
    builder.startTable(3);
    VideoCalibrationProgress.addTrackers(builder, trackersOffset);
    VideoCalibrationProgress.addCamera(builder, cameraOffset);
    VideoCalibrationProgress.addStatus(builder, status);
    return VideoCalibrationProgress.endVideoCalibrationProgress(builder);
  }

  public static void startVideoCalibrationProgress(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addStatus(FlatBufferBuilder builder, int status) { builder.addByte(0, (byte) status, (byte) 0); }
  public static void addCamera(FlatBufferBuilder builder, int cameraOffset) { builder.addOffset(1, cameraOffset, 0); }
  public static void addTrackers(FlatBufferBuilder builder, int trackersOffset) { builder.addOffset(2, trackersOffset, 0); }
  public static int createTrackersVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTrackersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endVideoCalibrationProgress(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public VideoCalibrationProgress get(int j) { return get(new VideoCalibrationProgress(), j); }
    public VideoCalibrationProgress get(VideoCalibrationProgress obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public VideoCalibrationProgressT unpack() {
    VideoCalibrationProgressT _o = new VideoCalibrationProgressT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(VideoCalibrationProgressT _o) {
    int _oStatus = status();
    _o.setStatus(_oStatus);
    if (camera() != null) _o.setCamera(camera().unpack());
    else _o.setCamera(null);
    solarxr_protocol.rpc.VideoCalibrationTrackerStatusT[] _oTrackers = new solarxr_protocol.rpc.VideoCalibrationTrackerStatusT[trackersLength()];
    for (int _j = 0; _j < trackersLength(); ++_j) {_oTrackers[_j] = (trackers(_j) != null ? trackers(_j).unpack() : null);}
    _o.setTrackers(_oTrackers);
  }
  public static int pack(FlatBufferBuilder builder, VideoCalibrationProgressT _o) {
    if (_o == null) return 0;
    int _camera = _o.getCamera() == null ? 0 : solarxr_protocol.rpc.VideoCalibrationCamera.pack(builder, _o.getCamera());
    int _trackers = 0;
    if (_o.getTrackers() != null) {
      int[] __trackers = new int[_o.getTrackers().length];
      int _j = 0;
      for (solarxr_protocol.rpc.VideoCalibrationTrackerStatusT _e : _o.getTrackers()) { __trackers[_j] = solarxr_protocol.rpc.VideoCalibrationTrackerStatus.pack(builder, _e); _j++;}
      _trackers = createTrackersVector(builder, __trackers);
    }
    return createVideoCalibrationProgress(
      builder,
      _o.getStatus(),
      _camera,
      _trackers);
  }
}

