// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class VideoCalibrationMissingTrackers extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static VideoCalibrationMissingTrackers getRootAsVideoCalibrationMissingTrackers(ByteBuffer _bb) { return getRootAsVideoCalibrationMissingTrackers(_bb, new VideoCalibrationMissingTrackers()); }
  public static VideoCalibrationMissingTrackers getRootAsVideoCalibrationMissingTrackers(ByteBuffer _bb, VideoCalibrationMissingTrackers obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public VideoCalibrationMissingTrackers __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int missingTrackers(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) & 0xFF : 0; }
  public int missingTrackersLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector missingTrackersVector() { return missingTrackersVector(new ByteVector()); }
  public ByteVector missingTrackersVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer missingTrackersAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer missingTrackersInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createVideoCalibrationMissingTrackers(FlatBufferBuilder builder,
      int missingTrackersOffset) {
    builder.startTable(1);
    VideoCalibrationMissingTrackers.addMissingTrackers(builder, missingTrackersOffset);
    return VideoCalibrationMissingTrackers.endVideoCalibrationMissingTrackers(builder);
  }

  public static void startVideoCalibrationMissingTrackers(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addMissingTrackers(FlatBufferBuilder builder, int missingTrackersOffset) { builder.addOffset(0, missingTrackersOffset, 0); }
  public static int createMissingTrackersVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createMissingTrackersVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startMissingTrackersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endVideoCalibrationMissingTrackers(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public VideoCalibrationMissingTrackers get(int j) { return get(new VideoCalibrationMissingTrackers(), j); }
    public VideoCalibrationMissingTrackers get(VideoCalibrationMissingTrackers obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public VideoCalibrationMissingTrackersT unpack() {
    VideoCalibrationMissingTrackersT _o = new VideoCalibrationMissingTrackersT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(VideoCalibrationMissingTrackersT _o) {
    int[] _oMissingTrackers = new int[missingTrackersLength()];
    for (int _j = 0; _j < missingTrackersLength(); ++_j) {_oMissingTrackers[_j] = missingTrackers(_j);}
    _o.setMissingTrackers(_oMissingTrackers);
  }
  public static int pack(FlatBufferBuilder builder, VideoCalibrationMissingTrackersT _o) {
    if (_o == null) return 0;
    int _missingTrackers = 0;
    if (_o.getMissingTrackers() != null) {
      byte[] __missingTrackers = new byte[_o.getMissingTrackers().length];
      int _j = 0;
      for (int _e : _o.getMissingTrackers()) { __missingTrackers[_j] = (byte) _e; _j++;}
      _missingTrackers = createMissingTrackersVector(builder, __missingTrackers);
    }
    return createVideoCalibrationMissingTrackers(
      builder,
      _missingTrackers);
  }
}

