// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

@SuppressWarnings("unused")
public final class VideoCalibrationProcess {
  private VideoCalibrationProcess() { }
  public static final int ALIGN_CAMERA = 0;
  public static final int ALIGN_TRACKERS = 1;
  public static final int OPTIMIZE_BODY_PROPORTIONS = 2;

  public static final String[] names = { "ALIGN_CAMERA", "ALIGN_TRACKERS", "OPTIMIZE_BODY_PROPORTIONS", };

  public static String name(int e) { return names[e]; }
}

