// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class VideoCalibrationProgressT {
  private int status;
  private solarxr_protocol.rpc.VideoCalibrationCameraT camera;
  private solarxr_protocol.rpc.VideoCalibrationTrackerStatusT[] trackers;

  public int getStatus() { return status; }

  public void setStatus(int status) { this.status = status; }

  public solarxr_protocol.rpc.VideoCalibrationCameraT getCamera() { return camera; }

  public void setCamera(solarxr_protocol.rpc.VideoCalibrationCameraT camera) { this.camera = camera; }

  public solarxr_protocol.rpc.VideoCalibrationTrackerStatusT[] getTrackers() { return trackers; }

  public void setTrackers(solarxr_protocol.rpc.VideoCalibrationTrackerStatusT[] trackers) { this.trackers = trackers; }


  public VideoCalibrationProgressT() {
    this.status = 0;
    this.camera = null;
    this.trackers = null;
  }
}

