// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class VideoCalibrationErrorT {
  private solarxr_protocol.rpc.VideoCalibrationMissingTrackersT missingPositionalTrackers;
  private solarxr_protocol.rpc.VideoCalibrationMissingTrackersT missingRequiredImuTrackers;
  private solarxr_protocol.rpc.VideoCalibrationForwardAndLeaningForwardNotAlignedT forwardAndLeaningForwardNotAligned;

  public solarxr_protocol.rpc.VideoCalibrationMissingTrackersT getMissingPositionalTrackers() { return missingPositionalTrackers; }

  public void setMissingPositionalTrackers(solarxr_protocol.rpc.VideoCalibrationMissingTrackersT missingPositionalTrackers) { this.missingPositionalTrackers = missingPositionalTrackers; }

  public solarxr_protocol.rpc.VideoCalibrationMissingTrackersT getMissingRequiredImuTrackers() { return missingRequiredImuTrackers; }

  public void setMissingRequiredImuTrackers(solarxr_protocol.rpc.VideoCalibrationMissingTrackersT missingRequiredImuTrackers) { this.missingRequiredImuTrackers = missingRequiredImuTrackers; }

  public solarxr_protocol.rpc.VideoCalibrationForwardAndLeaningForwardNotAlignedT getForwardAndLeaningForwardNotAligned() { return forwardAndLeaningForwardNotAligned; }

  public void setForwardAndLeaningForwardNotAligned(solarxr_protocol.rpc.VideoCalibrationForwardAndLeaningForwardNotAlignedT forwardAndLeaningForwardNotAligned) { this.forwardAndLeaningForwardNotAligned = forwardAndLeaningForwardNotAligned; }


  public VideoCalibrationErrorT() {
    this.missingPositionalTrackers = null;
    this.missingRequiredImuTrackers = null;
    this.forwardAndLeaningForwardNotAligned = null;
  }
}

