// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class VideoCalibrationForwardAndLeaningForwardNotAlignedT {
  private float yawDifference;

  public float getYawDifference() { return yawDifference; }

  public void setYawDifference(float yawDifference) { this.yawDifference = yawDifference; }


  public VideoCalibrationForwardAndLeaningForwardNotAlignedT() {
    this.yawDifference = 0.0f;
  }
}

