// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class YawCorrectionSettingsT {
  private boolean enabled;
  private float amountInDegPerSec;
  private boolean alignLegTrackers;
  private boolean alignLegTrackersToUpperBody;

  public boolean getEnabled() { return enabled; }

  public void setEnabled(boolean enabled) { this.enabled = enabled; }

  public float getAmountInDegPerSec() { return amountInDegPerSec; }

  public void setAmountInDegPerSec(float amountInDegPerSec) { this.amountInDegPerSec = amountInDegPerSec; }

  public boolean getAlignLegTrackers() { return alignLegTrackers; }

  public void setAlignLegTrackers(boolean alignLegTrackers) { this.alignLegTrackers = alignLegTrackers; }

  public boolean getAlignLegTrackersToUpperBody() { return alignLegTrackersToUpperBody; }

  public void setAlignLegTrackersToUpperBody(boolean alignLegTrackersToUpperBody) { this.alignLegTrackersToUpperBody = alignLegTrackersToUpperBody; }


  public YawCorrectionSettingsT() {
    this.enabled = false;
    this.amountInDegPerSec = 0.0f;
    this.alignLegTrackers = false;
    this.alignLegTrackersToUpperBody = false;
  }
}

