// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class YawCorrectionSettings extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static YawCorrectionSettings getRootAsYawCorrectionSettings(ByteBuffer _bb) { return getRootAsYawCorrectionSettings(_bb, new YawCorrectionSettings()); }
  public static YawCorrectionSettings getRootAsYawCorrectionSettings(ByteBuffer _bb, YawCorrectionSettings obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public YawCorrectionSettings __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean enabled() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public float amountInDegPerSec() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  /**
   * Relaxed body angles
   */
  public float standingUpperLegAngle() { int o = __offset(8); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float standingLowerLegAngle() { int o = __offset(10); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float standingFootAngle() { int o = __offset(12); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float sittingUpperLegAngle() { int o = __offset(14); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float sittingLowerLegAngle() { int o = __offset(16); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float sittingFootAngle() { int o = __offset(18); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float flatUpperLegAngle() { int o = __offset(20); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float flatLowerLegAngle() { int o = __offset(22); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float flatFootAngle() { int o = __offset(24); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }

  public static int createYawCorrectionSettings(FlatBufferBuilder builder,
      boolean enabled,
      float amountInDegPerSec,
      float standingUpperLegAngle,
      float standingLowerLegAngle,
      float standingFootAngle,
      float sittingUpperLegAngle,
      float sittingLowerLegAngle,
      float sittingFootAngle,
      float flatUpperLegAngle,
      float flatLowerLegAngle,
      float flatFootAngle) {
    builder.startTable(11);
    YawCorrectionSettings.addFlatFootAngle(builder, flatFootAngle);
    YawCorrectionSettings.addFlatLowerLegAngle(builder, flatLowerLegAngle);
    YawCorrectionSettings.addFlatUpperLegAngle(builder, flatUpperLegAngle);
    YawCorrectionSettings.addSittingFootAngle(builder, sittingFootAngle);
    YawCorrectionSettings.addSittingLowerLegAngle(builder, sittingLowerLegAngle);
    YawCorrectionSettings.addSittingUpperLegAngle(builder, sittingUpperLegAngle);
    YawCorrectionSettings.addStandingFootAngle(builder, standingFootAngle);
    YawCorrectionSettings.addStandingLowerLegAngle(builder, standingLowerLegAngle);
    YawCorrectionSettings.addStandingUpperLegAngle(builder, standingUpperLegAngle);
    YawCorrectionSettings.addAmountInDegPerSec(builder, amountInDegPerSec);
    YawCorrectionSettings.addEnabled(builder, enabled);
    return YawCorrectionSettings.endYawCorrectionSettings(builder);
  }

  public static void startYawCorrectionSettings(FlatBufferBuilder builder) { builder.startTable(11); }
  public static void addEnabled(FlatBufferBuilder builder, boolean enabled) { builder.addBoolean(0, enabled, false); }
  public static void addAmountInDegPerSec(FlatBufferBuilder builder, float amountInDegPerSec) { builder.addFloat(1, amountInDegPerSec, 0.0f); }
  public static void addStandingUpperLegAngle(FlatBufferBuilder builder, float standingUpperLegAngle) { builder.addFloat(2, standingUpperLegAngle, 0.0f); }
  public static void addStandingLowerLegAngle(FlatBufferBuilder builder, float standingLowerLegAngle) { builder.addFloat(3, standingLowerLegAngle, 0.0f); }
  public static void addStandingFootAngle(FlatBufferBuilder builder, float standingFootAngle) { builder.addFloat(4, standingFootAngle, 0.0f); }
  public static void addSittingUpperLegAngle(FlatBufferBuilder builder, float sittingUpperLegAngle) { builder.addFloat(5, sittingUpperLegAngle, 0.0f); }
  public static void addSittingLowerLegAngle(FlatBufferBuilder builder, float sittingLowerLegAngle) { builder.addFloat(6, sittingLowerLegAngle, 0.0f); }
  public static void addSittingFootAngle(FlatBufferBuilder builder, float sittingFootAngle) { builder.addFloat(7, sittingFootAngle, 0.0f); }
  public static void addFlatUpperLegAngle(FlatBufferBuilder builder, float flatUpperLegAngle) { builder.addFloat(8, flatUpperLegAngle, 0.0f); }
  public static void addFlatLowerLegAngle(FlatBufferBuilder builder, float flatLowerLegAngle) { builder.addFloat(9, flatLowerLegAngle, 0.0f); }
  public static void addFlatFootAngle(FlatBufferBuilder builder, float flatFootAngle) { builder.addFloat(10, flatFootAngle, 0.0f); }
  public static int endYawCorrectionSettings(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public YawCorrectionSettings get(int j) { return get(new YawCorrectionSettings(), j); }
    public YawCorrectionSettings get(YawCorrectionSettings obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public YawCorrectionSettingsT unpack() {
    YawCorrectionSettingsT _o = new YawCorrectionSettingsT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(YawCorrectionSettingsT _o) {
    boolean _oEnabled = enabled();
    _o.setEnabled(_oEnabled);
    float _oAmountInDegPerSec = amountInDegPerSec();
    _o.setAmountInDegPerSec(_oAmountInDegPerSec);
    float _oStandingUpperLegAngle = standingUpperLegAngle();
    _o.setStandingUpperLegAngle(_oStandingUpperLegAngle);
    float _oStandingLowerLegAngle = standingLowerLegAngle();
    _o.setStandingLowerLegAngle(_oStandingLowerLegAngle);
    float _oStandingFootAngle = standingFootAngle();
    _o.setStandingFootAngle(_oStandingFootAngle);
    float _oSittingUpperLegAngle = sittingUpperLegAngle();
    _o.setSittingUpperLegAngle(_oSittingUpperLegAngle);
    float _oSittingLowerLegAngle = sittingLowerLegAngle();
    _o.setSittingLowerLegAngle(_oSittingLowerLegAngle);
    float _oSittingFootAngle = sittingFootAngle();
    _o.setSittingFootAngle(_oSittingFootAngle);
    float _oFlatUpperLegAngle = flatUpperLegAngle();
    _o.setFlatUpperLegAngle(_oFlatUpperLegAngle);
    float _oFlatLowerLegAngle = flatLowerLegAngle();
    _o.setFlatLowerLegAngle(_oFlatLowerLegAngle);
    float _oFlatFootAngle = flatFootAngle();
    _o.setFlatFootAngle(_oFlatFootAngle);
  }
  public static int pack(FlatBufferBuilder builder, YawCorrectionSettingsT _o) {
    if (_o == null) return 0;
    return createYawCorrectionSettings(
      builder,
      _o.getEnabled(),
      _o.getAmountInDegPerSec(),
      _o.getStandingUpperLegAngle(),
      _o.getStandingLowerLegAngle(),
      _o.getStandingFootAngle(),
      _o.getSittingUpperLegAngle(),
      _o.getSittingLowerLegAngle(),
      _o.getSittingFootAngle(),
      _o.getFlatUpperLegAngle(),
      _o.getFlatLowerLegAngle(),
      _o.getFlatFootAngle());
  }
}

