// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class StayAlignedState implements flatbuffers.IUnpackableObject<StayAlignedStateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StayAlignedState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStayAlignedState(bb:flatbuffers.ByteBuffer, obj?:StayAlignedState):StayAlignedState {
  return (obj || new StayAlignedState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStayAlignedState(bb:flatbuffers.ByteBuffer, obj?:StayAlignedState):StayAlignedState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StayAlignedState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

yawCorrectionInDeg():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

lockedErrorInDeg():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

centerErrorInDeg():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

neighborErrorInDeg():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

locked():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startStayAlignedState(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addYawCorrectionInDeg(builder:flatbuffers.Builder, yawCorrectionInDeg:number) {
  builder.addFieldFloat32(0, yawCorrectionInDeg, 0.0);
}

static addLockedErrorInDeg(builder:flatbuffers.Builder, lockedErrorInDeg:number) {
  builder.addFieldFloat32(1, lockedErrorInDeg, 0.0);
}

static addCenterErrorInDeg(builder:flatbuffers.Builder, centerErrorInDeg:number) {
  builder.addFieldFloat32(2, centerErrorInDeg, 0.0);
}

static addNeighborErrorInDeg(builder:flatbuffers.Builder, neighborErrorInDeg:number) {
  builder.addFieldFloat32(3, neighborErrorInDeg, 0.0);
}

static addLocked(builder:flatbuffers.Builder, locked:boolean) {
  builder.addFieldInt8(4, +locked, +false);
}

static endStayAlignedState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStayAlignedState(builder:flatbuffers.Builder, yawCorrectionInDeg:number, lockedErrorInDeg:number, centerErrorInDeg:number, neighborErrorInDeg:number, locked:boolean):flatbuffers.Offset {
  StayAlignedState.startStayAlignedState(builder);
  StayAlignedState.addYawCorrectionInDeg(builder, yawCorrectionInDeg);
  StayAlignedState.addLockedErrorInDeg(builder, lockedErrorInDeg);
  StayAlignedState.addCenterErrorInDeg(builder, centerErrorInDeg);
  StayAlignedState.addNeighborErrorInDeg(builder, neighborErrorInDeg);
  StayAlignedState.addLocked(builder, locked);
  return StayAlignedState.endStayAlignedState(builder);
}

unpack(): StayAlignedStateT {
  return new StayAlignedStateT(
    this.yawCorrectionInDeg(),
    this.lockedErrorInDeg(),
    this.centerErrorInDeg(),
    this.neighborErrorInDeg(),
    this.locked()
  );
}


unpackTo(_o: StayAlignedStateT): void {
  _o.yawCorrectionInDeg = this.yawCorrectionInDeg();
  _o.lockedErrorInDeg = this.lockedErrorInDeg();
  _o.centerErrorInDeg = this.centerErrorInDeg();
  _o.neighborErrorInDeg = this.neighborErrorInDeg();
  _o.locked = this.locked();
}
}

export class StayAlignedStateT implements flatbuffers.IGeneratedObject {
constructor(
  public yawCorrectionInDeg: number = 0.0,
  public lockedErrorInDeg: number = 0.0,
  public centerErrorInDeg: number = 0.0,
  public neighborErrorInDeg: number = 0.0,
  public locked: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return StayAlignedState.createStayAlignedState(builder,
    this.yawCorrectionInDeg,
    this.lockedErrorInDeg,
    this.centerErrorInDeg,
    this.neighborErrorInDeg,
    this.locked
  );
}
}
