// automatically generated by the FlatBuffers compiler, do not modify

export enum StayAlignedPose {
  UNKNOWN = 0,
  STANDING = 1,
  SITTING_IN_CHAIR = 2,
  SITTING_ON_GROUND = 3,
  LYING_ON_BACK = 4,
  KNEELING = 5
}
