// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.data_feed.stay_aligned

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class StayAlignedData : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : StayAlignedData {
        __init(_i, _bb)
        return this
    }
    val upperLegAngleInDeg : Float
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val lowerLegAngleInDeg : Float
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val footAngleInDeg : Float
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsStayAlignedData(_bb: ByteBuffer): StayAlignedData = getRootAsStayAlignedData(_bb, StayAlignedData())
        @JvmStatic
        fun getRootAsStayAlignedData(_bb: ByteBuffer, obj: StayAlignedData): StayAlignedData {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun createStayAlignedData(builder: FlatBufferBuilder, upperLegAngleInDeg: Float, lowerLegAngleInDeg: Float, footAngleInDeg: Float) : Int {
            builder.startTable(3)
            addFootAngleInDeg(builder, footAngleInDeg)
            addLowerLegAngleInDeg(builder, lowerLegAngleInDeg)
            addUpperLegAngleInDeg(builder, upperLegAngleInDeg)
            return endStayAlignedData(builder)
        }
        @JvmStatic
        fun startStayAlignedData(builder: FlatBufferBuilder) = builder.startTable(3)
        @JvmStatic
        fun addUpperLegAngleInDeg(builder: FlatBufferBuilder, upperLegAngleInDeg: Float) = builder.addFloat(0, upperLegAngleInDeg, 0.0)
        @JvmStatic
        fun addLowerLegAngleInDeg(builder: FlatBufferBuilder, lowerLegAngleInDeg: Float) = builder.addFloat(1, lowerLegAngleInDeg, 0.0)
        @JvmStatic
        fun addFootAngleInDeg(builder: FlatBufferBuilder, footAngleInDeg: Float) = builder.addFloat(2, footAngleInDeg, 0.0)
        @JvmStatic
        fun endStayAlignedData(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
