// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.data_feed

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class StayAlignedState : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : StayAlignedState {
        __init(_i, _bb)
        return this
    }
    val yawCorrectionInDeg : Float
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val lockedErrorInDeg : Float
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val centerErrorInDeg : Float
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val neighborErrorInDeg : Float
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val locked : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsStayAlignedState(_bb: ByteBuffer): StayAlignedState = getRootAsStayAlignedState(_bb, StayAlignedState())
        @JvmStatic
        fun getRootAsStayAlignedState(_bb: ByteBuffer, obj: StayAlignedState): StayAlignedState {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun createStayAlignedState(builder: FlatBufferBuilder, yawCorrectionInDeg: Float, lockedErrorInDeg: Float, centerErrorInDeg: Float, neighborErrorInDeg: Float, locked: Boolean) : Int {
            builder.startTable(5)
            addNeighborErrorInDeg(builder, neighborErrorInDeg)
            addCenterErrorInDeg(builder, centerErrorInDeg)
            addLockedErrorInDeg(builder, lockedErrorInDeg)
            addYawCorrectionInDeg(builder, yawCorrectionInDeg)
            addLocked(builder, locked)
            return endStayAlignedState(builder)
        }
        @JvmStatic
        fun startStayAlignedState(builder: FlatBufferBuilder) = builder.startTable(5)
        @JvmStatic
        fun addYawCorrectionInDeg(builder: FlatBufferBuilder, yawCorrectionInDeg: Float) = builder.addFloat(0, yawCorrectionInDeg, 0.0)
        @JvmStatic
        fun addLockedErrorInDeg(builder: FlatBufferBuilder, lockedErrorInDeg: Float) = builder.addFloat(1, lockedErrorInDeg, 0.0)
        @JvmStatic
        fun addCenterErrorInDeg(builder: FlatBufferBuilder, centerErrorInDeg: Float) = builder.addFloat(2, centerErrorInDeg, 0.0)
        @JvmStatic
        fun addNeighborErrorInDeg(builder: FlatBufferBuilder, neighborErrorInDeg: Float) = builder.addFloat(3, neighborErrorInDeg, 0.0)
        @JvmStatic
        fun addLocked(builder: FlatBufferBuilder, locked: Boolean) = builder.addBoolean(4, locked, false)
        @JvmStatic
        fun endStayAlignedState(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
