// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.data_feed

@Suppress("unused")
class StayAlignedPose private constructor() {
    companion object {
        const val UNKNOWN: UByte = 0u
        const val STANDING: UByte = 1u
        const val SITTINGINCHAIR: UByte = 2u
        const val SITTINGONGROUND: UByte = 3u
        const val LYINGONBACK: UByte = 4u
        const val KNEELING: UByte = 5u
        val names : Array<String> = arrayOf("UNKNOWN", "STANDING", "SITTING_IN_CHAIR", "SITTING_ON_GROUND", "LYING_ON_BACK", "KNEELING")
        @JvmStatic
        fun name(e: Int) : String = names[e]
    }
}
