// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class StayAlignedData implements flatbuffers.IUnpackableObject<StayAlignedDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StayAlignedData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStayAlignedData(bb:flatbuffers.ByteBuffer, obj?:StayAlignedData):StayAlignedData {
  return (obj || new StayAlignedData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStayAlignedData(bb:flatbuffers.ByteBuffer, obj?:StayAlignedData):StayAlignedData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StayAlignedData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

upperLegAngleInDeg():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

lowerLegAngleInDeg():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

footAngleInDeg():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startStayAlignedData(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addUpperLegAngleInDeg(builder:flatbuffers.Builder, upperLegAngleInDeg:number) {
  builder.addFieldFloat32(0, upperLegAngleInDeg, 0.0);
}

static addLowerLegAngleInDeg(builder:flatbuffers.Builder, lowerLegAngleInDeg:number) {
  builder.addFieldFloat32(1, lowerLegAngleInDeg, 0.0);
}

static addFootAngleInDeg(builder:flatbuffers.Builder, footAngleInDeg:number) {
  builder.addFieldFloat32(2, footAngleInDeg, 0.0);
}

static endStayAlignedData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStayAlignedData(builder:flatbuffers.Builder, upperLegAngleInDeg:number, lowerLegAngleInDeg:number, footAngleInDeg:number):flatbuffers.Offset {
  StayAlignedData.startStayAlignedData(builder);
  StayAlignedData.addUpperLegAngleInDeg(builder, upperLegAngleInDeg);
  StayAlignedData.addLowerLegAngleInDeg(builder, lowerLegAngleInDeg);
  StayAlignedData.addFootAngleInDeg(builder, footAngleInDeg);
  return StayAlignedData.endStayAlignedData(builder);
}

unpack(): StayAlignedDataT {
  return new StayAlignedDataT(
    this.upperLegAngleInDeg(),
    this.lowerLegAngleInDeg(),
    this.footAngleInDeg()
  );
}


unpackTo(_o: StayAlignedDataT): void {
  _o.upperLegAngleInDeg = this.upperLegAngleInDeg();
  _o.lowerLegAngleInDeg = this.lowerLegAngleInDeg();
  _o.footAngleInDeg = this.footAngleInDeg();
}
}

export class StayAlignedDataT implements flatbuffers.IGeneratedObject {
constructor(
  public upperLegAngleInDeg: number = 0.0,
  public lowerLegAngleInDeg: number = 0.0,
  public footAngleInDeg: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return StayAlignedData.createStayAlignedData(builder,
    this.upperLegAngleInDeg,
    this.lowerLegAngleInDeg,
    this.footAngleInDeg
  );
}
}
