// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.data_feed;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class DataFeedUpdateT {
  private solarxr_protocol.data_feed.device_data.DeviceDataT[] devices;
  private solarxr_protocol.data_feed.tracker.TrackerDataT[] syntheticTrackers;
  private solarxr_protocol.data_feed.BoneT[] bones;
  private solarxr_protocol.data_feed.stay_aligned.StayAlignedDataT stayAligned;

  public solarxr_protocol.data_feed.device_data.DeviceDataT[] getDevices() { return devices; }

  public void setDevices(solarxr_protocol.data_feed.device_data.DeviceDataT[] devices) { this.devices = devices; }

  public solarxr_protocol.data_feed.tracker.TrackerDataT[] getSyntheticTrackers() { return syntheticTrackers; }

  public void setSyntheticTrackers(solarxr_protocol.data_feed.tracker.TrackerDataT[] syntheticTrackers) { this.syntheticTrackers = syntheticTrackers; }

  public solarxr_protocol.data_feed.BoneT[] getBones() { return bones; }

  public void setBones(solarxr_protocol.data_feed.BoneT[] bones) { this.bones = bones; }

  public solarxr_protocol.data_feed.stay_aligned.StayAlignedDataT getStayAligned() { return stayAligned; }

  public void setStayAligned(solarxr_protocol.data_feed.stay_aligned.StayAlignedDataT stayAligned) { this.stayAligned = stayAligned; }


  public DataFeedUpdateT() {
    this.devices = null;
    this.syntheticTrackers = null;
    this.bones = null;
    this.stayAligned = null;
  }
}

