// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.data_feed;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StayAlignedState extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static StayAlignedState getRootAsStayAlignedState(ByteBuffer _bb) { return getRootAsStayAlignedState(_bb, new StayAlignedState()); }
  public static StayAlignedState getRootAsStayAlignedState(ByteBuffer _bb, StayAlignedState obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StayAlignedState __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float yawCorrectionInDeg() { int o = __offset(4); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float lockedErrorInDeg() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float centerErrorInDeg() { int o = __offset(8); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public float neighborErrorInDeg() { int o = __offset(10); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public boolean locked() { int o = __offset(12); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createStayAlignedState(FlatBufferBuilder builder,
      float yawCorrectionInDeg,
      float lockedErrorInDeg,
      float centerErrorInDeg,
      float neighborErrorInDeg,
      boolean locked) {
    builder.startTable(5);
    StayAlignedState.addNeighborErrorInDeg(builder, neighborErrorInDeg);
    StayAlignedState.addCenterErrorInDeg(builder, centerErrorInDeg);
    StayAlignedState.addLockedErrorInDeg(builder, lockedErrorInDeg);
    StayAlignedState.addYawCorrectionInDeg(builder, yawCorrectionInDeg);
    StayAlignedState.addLocked(builder, locked);
    return StayAlignedState.endStayAlignedState(builder);
  }

  public static void startStayAlignedState(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addYawCorrectionInDeg(FlatBufferBuilder builder, float yawCorrectionInDeg) { builder.addFloat(0, yawCorrectionInDeg, 0.0f); }
  public static void addLockedErrorInDeg(FlatBufferBuilder builder, float lockedErrorInDeg) { builder.addFloat(1, lockedErrorInDeg, 0.0f); }
  public static void addCenterErrorInDeg(FlatBufferBuilder builder, float centerErrorInDeg) { builder.addFloat(2, centerErrorInDeg, 0.0f); }
  public static void addNeighborErrorInDeg(FlatBufferBuilder builder, float neighborErrorInDeg) { builder.addFloat(3, neighborErrorInDeg, 0.0f); }
  public static void addLocked(FlatBufferBuilder builder, boolean locked) { builder.addBoolean(4, locked, false); }
  public static int endStayAlignedState(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StayAlignedState get(int j) { return get(new StayAlignedState(), j); }
    public StayAlignedState get(StayAlignedState obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public StayAlignedStateT unpack() {
    StayAlignedStateT _o = new StayAlignedStateT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(StayAlignedStateT _o) {
    float _oYawCorrectionInDeg = yawCorrectionInDeg();
    _o.setYawCorrectionInDeg(_oYawCorrectionInDeg);
    float _oLockedErrorInDeg = lockedErrorInDeg();
    _o.setLockedErrorInDeg(_oLockedErrorInDeg);
    float _oCenterErrorInDeg = centerErrorInDeg();
    _o.setCenterErrorInDeg(_oCenterErrorInDeg);
    float _oNeighborErrorInDeg = neighborErrorInDeg();
    _o.setNeighborErrorInDeg(_oNeighborErrorInDeg);
    boolean _oLocked = locked();
    _o.setLocked(_oLocked);
  }
  public static int pack(FlatBufferBuilder builder, StayAlignedStateT _o) {
    if (_o == null) return 0;
    return createStayAlignedState(
      builder,
      _o.getYawCorrectionInDeg(),
      _o.getLockedErrorInDeg(),
      _o.getCenterErrorInDeg(),
      _o.getNeighborErrorInDeg(),
      _o.getLocked());
  }
}

