// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.data_feed;

@SuppressWarnings("unused")
public final class StayAlignedPose {
  private StayAlignedPose() { }
  public static final int UNKNOWN = 0;
  public static final int STANDING = 1;
  public static final int SITTING_IN_CHAIR = 2;
  public static final int SITTING_ON_GROUND = 3;
  public static final int LYING_ON_BACK = 4;
  public static final int KNEELING = 5;

  public static final String[] names = { "UNKNOWN", "STANDING", "SITTING_IN_CHAIR", "SITTING_ON_GROUND", "LYING_ON_BACK", "KNEELING", };

  public static String name(int e) { return names[e]; }
}

