// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class ConnectToVideoCalibrationRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ConnectToVideoCalibrationRequest {
        __init(_i, _bb)
        return this
    }
    val offerSdp : String?
        get() {
            val o = __offset(4)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val offerSdpAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun offerSdpInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsConnectToVideoCalibrationRequest(_bb: ByteBuffer): ConnectToVideoCalibrationRequest = getRootAsConnectToVideoCalibrationRequest(_bb, ConnectToVideoCalibrationRequest())
        @JvmStatic
        fun getRootAsConnectToVideoCalibrationRequest(_bb: ByteBuffer, obj: ConnectToVideoCalibrationRequest): ConnectToVideoCalibrationRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun createConnectToVideoCalibrationRequest(builder: FlatBufferBuilder, offerSdpOffset: Int) : Int {
            builder.startTable(1)
            addOfferSdp(builder, offerSdpOffset)
            return endConnectToVideoCalibrationRequest(builder)
        }
        @JvmStatic
        fun startConnectToVideoCalibrationRequest(builder: FlatBufferBuilder) = builder.startTable(1)
        @JvmStatic
        fun addOfferSdp(builder: FlatBufferBuilder, offerSdp: Int) = builder.addOffset(0, offerSdp, 0)
        @JvmStatic
        fun endConnectToVideoCalibrationRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
