// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class RecordPFSRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : RecordPFSRequest {
        __init(_i, _bb)
        return this
    }
    val durationSec : Float
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val intervalSec : Float
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsRecordPFSRequest(_bb: ByteBuffer): RecordPFSRequest = getRootAsRecordPFSRequest(_bb, RecordPFSRequest())
        @JvmStatic
        fun getRootAsRecordPFSRequest(_bb: ByteBuffer, obj: RecordPFSRequest): RecordPFSRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun createRecordPFSRequest(builder: FlatBufferBuilder, durationSec: Float, intervalSec: Float) : Int {
            builder.startTable(2)
            addIntervalSec(builder, intervalSec)
            addDurationSec(builder, durationSec)
            return endRecordPFSRequest(builder)
        }
        @JvmStatic
        fun startRecordPFSRequest(builder: FlatBufferBuilder) = builder.startTable(2)
        @JvmStatic
        fun addDurationSec(builder: FlatBufferBuilder, durationSec: Float) = builder.addFloat(0, durationSec, 0.0)
        @JvmStatic
        fun addIntervalSec(builder: FlatBufferBuilder, intervalSec: Float) = builder.addFloat(1, intervalSec, 0.0)
        @JvmStatic
        fun endRecordPFSRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
