// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class RecordPFSResponse : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : RecordPFSResponse {
        __init(_i, _bb)
        return this
    }
    fun data(j: Int) : UByte {
        val o = __offset(4)
        return if (o != 0) {
            bb.get(__vector(o) + j * 1).toUByte()
        } else {
            0u
        }
    }
    val dataLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    val dataAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun dataInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsRecordPFSResponse(_bb: ByteBuffer): RecordPFSResponse = getRootAsRecordPFSResponse(_bb, RecordPFSResponse())
        @JvmStatic
        fun getRootAsRecordPFSResponse(_bb: ByteBuffer, obj: RecordPFSResponse): RecordPFSResponse {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun createRecordPFSResponse(builder: FlatBufferBuilder, dataOffset: Int) : Int {
            builder.startTable(1)
            addData(builder, dataOffset)
            return endRecordPFSResponse(builder)
        }
        @JvmStatic
        fun startRecordPFSResponse(builder: FlatBufferBuilder) = builder.startTable(1)
        @JvmStatic
        fun addData(builder: FlatBufferBuilder, data: Int) = builder.addOffset(0, data, 0)
        @JvmStatic
        fun createDataVector(builder: FlatBufferBuilder, data: UByteArray) : Int {
            builder.startVector(1, data.size, 1)
            for (i in data.size - 1 downTo 0) {
                builder.addByte(data[i].toByte())
            }
            return builder.endVector()
        }
        @JvmStatic
        fun startDataVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(1, numElems, 1)
        @JvmStatic
        fun endRecordPFSResponse(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
