// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

@Suppress("unused")
class ResetBodyPose private constructor() {
    companion object {
        const val SKIING: UByte = 0u
        const val SITTINGLEANINGBACK: UByte = 1u
        val names : Array<String> = arrayOf("SKIING", "SITTING_LEANING_BACK")
        @JvmStatic
        fun name(e: Int) : String = names[e]
    }
}
