// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class StartVideoCalibrationRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : StartVideoCalibrationRequest {
        __init(_i, _bb)
        return this
    }
    val process : UByte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsStartVideoCalibrationRequest(_bb: ByteBuffer): StartVideoCalibrationRequest = getRootAsStartVideoCalibrationRequest(_bb, StartVideoCalibrationRequest())
        @JvmStatic
        fun getRootAsStartVideoCalibrationRequest(_bb: ByteBuffer, obj: StartVideoCalibrationRequest): StartVideoCalibrationRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun createStartVideoCalibrationRequest(builder: FlatBufferBuilder, process: UByte) : Int {
            builder.startTable(1)
            addProcess(builder, process)
            return endStartVideoCalibrationRequest(builder)
        }
        @JvmStatic
        fun startStartVideoCalibrationRequest(builder: FlatBufferBuilder) = builder.startTable(1)
        @JvmStatic
        fun addProcess(builder: FlatBufferBuilder, process: UByte) = builder.addByte(0, process.toByte(), 0)
        @JvmStatic
        fun endStartVideoCalibrationRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
