// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class VideoCalibrationTrackerStatus : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : VideoCalibrationTrackerStatus {
        __init(_i, _bb)
        return this
    }
    val bodyPart : UByte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val aligned : Boolean
        get() {
            val o = __offset(6)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsVideoCalibrationTrackerStatus(_bb: ByteBuffer): VideoCalibrationTrackerStatus = getRootAsVideoCalibrationTrackerStatus(_bb, VideoCalibrationTrackerStatus())
        @JvmStatic
        fun getRootAsVideoCalibrationTrackerStatus(_bb: ByteBuffer, obj: VideoCalibrationTrackerStatus): VideoCalibrationTrackerStatus {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun createVideoCalibrationTrackerStatus(builder: FlatBufferBuilder, bodyPart: UByte, aligned: Boolean) : Int {
            builder.startTable(2)
            addAligned(builder, aligned)
            addBodyPart(builder, bodyPart)
            return endVideoCalibrationTrackerStatus(builder)
        }
        @JvmStatic
        fun startVideoCalibrationTrackerStatus(builder: FlatBufferBuilder) = builder.startTable(2)
        @JvmStatic
        fun addBodyPart(builder: FlatBufferBuilder, bodyPart: UByte) = builder.addByte(0, bodyPart.toByte(), 0)
        @JvmStatic
        fun addAligned(builder: FlatBufferBuilder, aligned: Boolean) = builder.addBoolean(1, aligned, false)
        @JvmStatic
        fun endVideoCalibrationTrackerStatus(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
