// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class VideoCalibrationMissingTrackers : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : VideoCalibrationMissingTrackers {
        __init(_i, _bb)
        return this
    }
    fun missingTrackers(j: Int) : UByte {
        val o = __offset(4)
        return if (o != 0) {
            bb.get(__vector(o) + j * 1).toUByte()
        } else {
            0u
        }
    }
    val missingTrackersLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    val missingTrackersAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun missingTrackersInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsVideoCalibrationMissingTrackers(_bb: ByteBuffer): VideoCalibrationMissingTrackers = getRootAsVideoCalibrationMissingTrackers(_bb, VideoCalibrationMissingTrackers())
        @JvmStatic
        fun getRootAsVideoCalibrationMissingTrackers(_bb: ByteBuffer, obj: VideoCalibrationMissingTrackers): VideoCalibrationMissingTrackers {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun createVideoCalibrationMissingTrackers(builder: FlatBufferBuilder, missingTrackersOffset: Int) : Int {
            builder.startTable(1)
            addMissingTrackers(builder, missingTrackersOffset)
            return endVideoCalibrationMissingTrackers(builder)
        }
        @JvmStatic
        fun startVideoCalibrationMissingTrackers(builder: FlatBufferBuilder) = builder.startTable(1)
        @JvmStatic
        fun addMissingTrackers(builder: FlatBufferBuilder, missingTrackers: Int) = builder.addOffset(0, missingTrackers, 0)
        @JvmStatic
        fun createMissingTrackersVector(builder: FlatBufferBuilder, data: UByteArray) : Int {
            builder.startVector(1, data.size, 1)
            for (i in data.size - 1 downTo 0) {
                builder.addByte(data[i].toByte())
            }
            return builder.endVector()
        }
        @JvmStatic
        fun startMissingTrackersVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(1, numElems, 1)
        @JvmStatic
        fun endVideoCalibrationMissingTrackers(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
