// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

@Suppress("unused")
class VideoCalibrationStatus private constructor() {
    companion object {
        const val NOTSTARTED: UByte = 0u
        const val CONNECTINGTOSERVER: UByte = 1u
        const val CONNECTINGTOWEBCAM: UByte = 2u
        const val WAITINGFORUSERSTART: UByte = 3u
        const val SOLVINGCAMERAEXTRINSIC: UByte = 4u
        const val CAPTURINGFORWARDPOSE: UByte = 5u
        const val CAPTURINGLEANINGFORWARDPOSE: UByte = 6u
        const val ALIGNINGUPPERBODYTRACKERS: UByte = 7u
        const val ALIGNINGREMAININGTRACKERS: UByte = 8u
        const val OPTIMIZINGBODYPROPORTIONS: UByte = 9u
        const val COMPLETE: UByte = 10u
        val names : Array<String> = arrayOf("NOT_STARTED", "CONNECTING_TO_SERVER", "CONNECTING_TO_WEBCAM", "WAITING_FOR_USER_START", "SOLVING_CAMERA_EXTRINSIC", "CAPTURING_FORWARD_POSE", "CAPTURING_LEANING_FORWARD_POSE", "ALIGNING_UPPER_BODY_TRACKERS", "ALIGNING_REMAINING_TRACKERS", "OPTIMIZING_BODY_PROPORTIONS", "COMPLETE")
        @JvmStatic
        fun name(e: Int) : String = names[e]
    }
}
