// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

@Suppress("unused")
class VideoCalibrationProcess private constructor() {
    companion object {
        const val ALIGNCAMERA: UByte = 0u
        const val ALIGNTRACKERS: UByte = 1u
        const val OPTIMIZEBODYPROPORTIONS: UByte = 2u
        val names : Array<String> = arrayOf("ALIGN_CAMERA", "ALIGN_TRACKERS", "OPTIMIZE_BODY_PROPORTIONS")
        @JvmStatic
        fun name(e: Int) : String = names[e]
    }
}
