// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class VideoCalibrationProgress : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : VideoCalibrationProgress {
        __init(_i, _bb)
        return this
    }
    val status : UByte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val camera : solarxr_protocol.rpc.VideoCalibrationCamera? get() = camera(solarxr_protocol.rpc.VideoCalibrationCamera())
    fun camera(obj: solarxr_protocol.rpc.VideoCalibrationCamera) : solarxr_protocol.rpc.VideoCalibrationCamera? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun trackers(j: Int) : solarxr_protocol.rpc.VideoCalibrationTrackerStatus? = trackers(solarxr_protocol.rpc.VideoCalibrationTrackerStatus(), j)
    fun trackers(obj: solarxr_protocol.rpc.VideoCalibrationTrackerStatus, j: Int) : solarxr_protocol.rpc.VideoCalibrationTrackerStatus? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val trackersLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsVideoCalibrationProgress(_bb: ByteBuffer): VideoCalibrationProgress = getRootAsVideoCalibrationProgress(_bb, VideoCalibrationProgress())
        @JvmStatic
        fun getRootAsVideoCalibrationProgress(_bb: ByteBuffer, obj: VideoCalibrationProgress): VideoCalibrationProgress {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun createVideoCalibrationProgress(builder: FlatBufferBuilder, status: UByte, cameraOffset: Int, trackersOffset: Int) : Int {
            builder.startTable(3)
            addTrackers(builder, trackersOffset)
            addCamera(builder, cameraOffset)
            addStatus(builder, status)
            return endVideoCalibrationProgress(builder)
        }
        @JvmStatic
        fun startVideoCalibrationProgress(builder: FlatBufferBuilder) = builder.startTable(3)
        @JvmStatic
        fun addStatus(builder: FlatBufferBuilder, status: UByte) = builder.addByte(0, status.toByte(), 0)
        @JvmStatic
        fun addCamera(builder: FlatBufferBuilder, camera: Int) = builder.addOffset(1, camera, 0)
        @JvmStatic
        fun addTrackers(builder: FlatBufferBuilder, trackers: Int) = builder.addOffset(2, trackers, 0)
        @JvmStatic
        fun createTrackersVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        @JvmStatic
        fun startTrackersVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        @JvmStatic
        fun endVideoCalibrationProgress(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
