// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class VideoCalibrationError : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : VideoCalibrationError {
        __init(_i, _bb)
        return this
    }
    val missingPositionalTrackers : solarxr_protocol.rpc.VideoCalibrationMissingTrackers? get() = missingPositionalTrackers(solarxr_protocol.rpc.VideoCalibrationMissingTrackers())
    fun missingPositionalTrackers(obj: solarxr_protocol.rpc.VideoCalibrationMissingTrackers) : solarxr_protocol.rpc.VideoCalibrationMissingTrackers? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val missingRequiredImuTrackers : solarxr_protocol.rpc.VideoCalibrationMissingTrackers? get() = missingRequiredImuTrackers(solarxr_protocol.rpc.VideoCalibrationMissingTrackers())
    fun missingRequiredImuTrackers(obj: solarxr_protocol.rpc.VideoCalibrationMissingTrackers) : solarxr_protocol.rpc.VideoCalibrationMissingTrackers? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val forwardAndLeaningForwardNotAligned : solarxr_protocol.rpc.VideoCalibrationForwardAndLeaningForwardNotAligned? get() = forwardAndLeaningForwardNotAligned(solarxr_protocol.rpc.VideoCalibrationForwardAndLeaningForwardNotAligned())
    fun forwardAndLeaningForwardNotAligned(obj: solarxr_protocol.rpc.VideoCalibrationForwardAndLeaningForwardNotAligned) : solarxr_protocol.rpc.VideoCalibrationForwardAndLeaningForwardNotAligned? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsVideoCalibrationError(_bb: ByteBuffer): VideoCalibrationError = getRootAsVideoCalibrationError(_bb, VideoCalibrationError())
        @JvmStatic
        fun getRootAsVideoCalibrationError(_bb: ByteBuffer, obj: VideoCalibrationError): VideoCalibrationError {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun createVideoCalibrationError(builder: FlatBufferBuilder, missingPositionalTrackersOffset: Int, missingRequiredImuTrackersOffset: Int, forwardAndLeaningForwardNotAlignedOffset: Int) : Int {
            builder.startTable(3)
            addForwardAndLeaningForwardNotAligned(builder, forwardAndLeaningForwardNotAlignedOffset)
            addMissingRequiredImuTrackers(builder, missingRequiredImuTrackersOffset)
            addMissingPositionalTrackers(builder, missingPositionalTrackersOffset)
            return endVideoCalibrationError(builder)
        }
        @JvmStatic
        fun startVideoCalibrationError(builder: FlatBufferBuilder) = builder.startTable(3)
        @JvmStatic
        fun addMissingPositionalTrackers(builder: FlatBufferBuilder, missingPositionalTrackers: Int) = builder.addOffset(0, missingPositionalTrackers, 0)
        @JvmStatic
        fun addMissingRequiredImuTrackers(builder: FlatBufferBuilder, missingRequiredImuTrackers: Int) = builder.addOffset(1, missingRequiredImuTrackers, 0)
        @JvmStatic
        fun addForwardAndLeaningForwardNotAligned(builder: FlatBufferBuilder, forwardAndLeaningForwardNotAligned: Int) = builder.addOffset(2, forwardAndLeaningForwardNotAligned, 0)
        @JvmStatic
        fun endVideoCalibrationError(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
