// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class VideoCalibrationForwardAndLeaningForwardNotAligned : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : VideoCalibrationForwardAndLeaningForwardNotAligned {
        __init(_i, _bb)
        return this
    }
    val yawDifference : Float
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsVideoCalibrationForwardAndLeaningForwardNotAligned(_bb: ByteBuffer): VideoCalibrationForwardAndLeaningForwardNotAligned = getRootAsVideoCalibrationForwardAndLeaningForwardNotAligned(_bb, VideoCalibrationForwardAndLeaningForwardNotAligned())
        @JvmStatic
        fun getRootAsVideoCalibrationForwardAndLeaningForwardNotAligned(_bb: ByteBuffer, obj: VideoCalibrationForwardAndLeaningForwardNotAligned): VideoCalibrationForwardAndLeaningForwardNotAligned {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun createVideoCalibrationForwardAndLeaningForwardNotAligned(builder: FlatBufferBuilder, yawDifference: Float) : Int {
            builder.startTable(1)
            addYawDifference(builder, yawDifference)
            return endVideoCalibrationForwardAndLeaningForwardNotAligned(builder)
        }
        @JvmStatic
        fun startVideoCalibrationForwardAndLeaningForwardNotAligned(builder: FlatBufferBuilder) = builder.startTable(1)
        @JvmStatic
        fun addYawDifference(builder: FlatBufferBuilder, yawDifference: Float) = builder.addFloat(0, yawDifference, 0.0)
        @JvmStatic
        fun endVideoCalibrationForwardAndLeaningForwardNotAligned(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
